#!/usr/bin/env python3
"""Generate the T-105 golden from Nepal's official National Panchang (Rashtriya Panchangam) for BS 2082 and 2083.

Publisher: Nepal Panchanga Nirnayak Vikas Samiti (Government of Nepal), https://npns.gov.np/. The yearly PDFs are
scanned pages without a text layer, so the values below were read from the page images: for each month the Gregorian
date of its first day (and the printed weekday) from the month's first page, and the time of the Sun's entry into the
sign (NPT) from the "ग्रहचार/उदयास्त" box of that page. The script checks them for internal consistency (weekdays,
contiguous 365/366-day years, sankranti on or next to the first day) and, given the directory of the downloaded PDFs,
their SHA-256. The PDFs are cited, not stored. Usage: national_panchang.py [pdf dir] [--check]
"""
import datetime, hashlib, pathlib, sys

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = REPO / "core/calendar/src/test/resources/golden/nepal/national-panchang-2082-2083.csv"
SOURCES = {
    2082: ("https://giwmscdnone.gov.np/media/pages/files/npnbs_2082_ussfian.pdf", "npns2082.pdf",
           "e0b9aad80b85a8863daba0b5cc20150dca483df90365fc6d93cdafcdd3dd2848"),
    2083: ("https://giwmscdnone.gov.np/media/pages/files/FORMAT-2083-A_7f75xmb.pdf", "npns2083.pdf",
           "e7615a149018edd41e6239f7d0ed0c513f94e0566277dca7af41347c62713bde"),
}
# (BS year, month, page, first day, printed weekday, sankranti date NPT, hour, minute)
ROWS = [
    (2082, 1, 2, "2025-04-14", "Mon", "2025-04-14", 5, 51), (2082, 2, 4, "2025-05-15", "Thu", "2025-05-15", 4, 17),
    (2082, 3, 6, "2025-06-15", "Sun", "2025-06-15", 14, 22), (2082, 4, 8, "2025-07-17", "Thu", "2025-07-17", 5, 50),
    (2082, 5, 10, "2025-08-17", "Sun", "2025-08-17", 17, 15), (2082, 6, 12, "2025-09-17", "Wed", "2025-09-17", 17, 43),
    (2082, 7, 14, "2025-10-18", "Sat", "2025-10-18", 4, 19), (2082, 8, 16, "2025-11-17", "Mon", "2025-11-17", 1, 46),
    (2082, 9, 18, "2025-12-16", "Tue", "2025-12-16", 13, 33), (2082, 10, 20, "2026-01-15", "Thu", "2026-01-14", 21, 10),
    (2082, 11, 22, "2026-02-13", "Fri", "2026-02-13", 7, 55), (2082, 12, 24, "2026-03-15", "Sun", "2026-03-15", 3, 36),
    (2083, 1, 2, "2026-04-14", "Tue", "2026-04-14", 12, 4), (2083, 2, 4, "2026-05-15", "Fri", "2026-05-15", 10, 30),
    (2083, 3, 6, "2026-06-15", "Mon", "2026-06-15", 20, 35), (2083, 4, 9, "2026-07-17", "Fri", "2026-07-17", 12, 3),
    (2083, 5, 11, "2026-08-17", "Mon", "2026-08-17", 23, 28), (2083, 6, 13, "2026-09-17", "Thu", "2026-09-17", 23, 55),
    (2083, 7, 15, "2026-10-18", "Sun", "2026-10-18", 10, 32), (2083, 8, 17, "2026-11-17", "Tue", "2026-11-17", 7, 59),
    (2083, 9, 19, "2026-12-16", "Wed", "2026-12-16", 19, 45), (2083, 10, 21, "2027-01-15", "Fri", "2027-01-15", 3, 23),
    (2083, 11, 23, "2027-02-13", "Sat", "2027-02-13", 14, 7), (2083, 12, 25, "2027-03-15", "Mon", "2027-03-15", 9, 48),
]
# First day of the following year, printed as the last row of each book (2082 p. 26, 2083 p. 27).
YEAR_ENDS = {2082: "2026-04-14", 2083: "2027-04-14"}


def check(directory: pathlib.Path | None) -> None:
    for year, (_, name, digest) in SOURCES.items():
        if directory is not None and hashlib.sha256((directory / name).read_bytes()).hexdigest() != digest:
            sys.exit(f"{name}: SHA-256 differs from the cited copy")
    for year in SOURCES:
        starts = [datetime.date.fromisoformat(r[3]) for r in ROWS if r[0] == year]
        starts.append(datetime.date.fromisoformat(YEAR_ENDS[year]))
        lengths = [(b - a).days for a, b in zip(starts, starts[1:])]
        assert len(lengths) == 12 and all(29 <= n <= 32 for n in lengths) and sum(lengths) in (365, 366), lengths
    for row in ROWS:
        first = datetime.date.fromisoformat(row[3])
        assert first.strftime("%a") == row[4], row
        assert 0 <= (first - datetime.date.fromisoformat(row[5])).days <= 1, row


def render() -> str:
    header = [
        "# source: Nepal Panchanga Nirnayak Vikas Samiti, Rashtriya Panchangam BS 2082 and 2083 (Government of Nepal)",
        "# url: https://npns.gov.np/",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        f"# notes: PDFs {SOURCES[2082][0]} (sha256={SOURCES[2082][2]}) and {SOURCES[2083][0]} "
        f"(sha256={SOURCES[2083][2]}), cited not stored; read from the scanned page images (no text layer); "
        "sankranti times are Nepal Standard Time (UTC+05:45) to the minute; generated by tools/nepal/national_panchang.py",
        "bs_year,month,page,first_day,weekday,sankranti_date,sankranti_time",
    ]
    lines = [f"{y},{m},{p},{d},{w},{sd},{h:02d}:{mi:02d}" for (y, m, p, d, w, sd, h, mi) in ROWS]
    lines += [f"{y + 1},1,{27 if y == 2083 else 26},{d},,," for y, d in YEAR_ENDS.items() if y == 2083]
    return "\n".join(header + lines) + "\n"


def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check(pathlib.Path(args[0]) if args else None)
    text = render()
    if "--check" in sys.argv:
        if GOLDEN.read_text() != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date")
        print("up to date")
        return
    GOLDEN.write_text(text)
    print(f"{len(ROWS)} rows written")


if __name__ == "__main__":
    main()
