#!/usr/bin/env python3
"""Generate the T-105 golden of Bikram Sambat month starts printed by the Nepal Telecommunications Authority.

Each monthly NTA MIS report (https://nta.gov.np/uploads/contents/MIS-<BS year>-<month>.pdf) states the Gregorian dates
its BS month spans on page 1, e.g. "Shrawan, 2074 (16 July 2017 – 16 August 2017)". This script reads the reports from
a local directory (download them first; the reports are not stored in the repository), extracts the first day of each
month and writes one row per month with the report's URL and SHA-256. Reports before BS 2070 print approximate
"15 – 14" ranges and are skipped. Usage: nta_month_starts.py <pdf dir> [--check]
"""
import datetime, hashlib, pathlib, re, subprocess, sys

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = REPO / "core/calendar/src/test/resources/golden/nepal/nta-month-starts.csv"
URL = "https://nta.gov.np/uploads/contents/{}"
FIRST_YEAR = 2070
MONTHS = {"baisakh": 1, "baishakh": 1, "jestha": 2, "asar": 3, "ashad": 3, "ashadh": 3, "shrawan": 4, "bhadra": 5,
          "asoj": 6, "ashoj": 6, "ashwin": 6, "kartik": 7, "mangsir": 8, "poush": 9, "paush": 9, "magh": 10,
          "falgun": 11, "chaitra": 12}
# Gregorian months by their first three letters (the reports contain spellings such as "Septmber").
GREGORIAN = {name: number for number, name in enumerate(
    ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"], 1)}
RANGE = re.compile(
    r"\(\s*(\d{1,2})\s*,?\s*([A-Za-z]+)\s*,?\s*(\d{4})?\s*[–-]+\s*\d{1,2}\s*,?\s*([A-Za-z]+)\s*,?\s*(\d{4})"
)


def first_day(path: pathlib.Path) -> datetime.date | None:
    """The first day of the report's month, or None when page 1 prints no date range (a format notice)."""
    text = subprocess.run(["pdftotext", "-layout", "-l", "1", str(path), "-"], capture_output=True, text=True,
                          check=True).stdout
    match = RANGE.search(re.sub(r"\s+", " ", text))
    if match is None:
        return None
    day, month = int(match.group(1)), GREGORIAN[match.group(2).lower()[:3]]
    end_month, end_year = GREGORIAN[match.group(4).lower()[:3]], int(match.group(5))
    year = int(match.group(3)) if match.group(3) else end_year - (1 if month > end_month else 0)
    return datetime.date(year, month, day)


def rows(directory: pathlib.Path) -> list[str]:
    found = {}
    for path in sorted(directory.glob("MIS-*.pdf")):
        _, bs_year, name = path.stem.split("-")
        key = (int(bs_year), MONTHS[name.lower()])
        if key[0] < FIRST_YEAR or key in found:
            continue
        start = first_day(path)
        if start is None:
            print(f"skipped {path.name}: no date range on page 1", file=sys.stderr)
            continue
        expected_year = key[0] - (56 if key[1] >= 10 else 57)
        if abs(start.year - expected_year) > 1:
            raise ValueError(f"{path.name}: implausible year {start}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        found[key] = f"{key[0]},{key[1]},{start.isoformat()},{URL.format(path.name)},{digest}"
    return [found[key] for key in sorted(found)]


def render(directory: pathlib.Path) -> str:
    header = [
        "# source: Nepal Telecommunications Authority, monthly MIS reports (Government of Nepal), page 1 month ranges",
        "# url: https://nta.gov.np/",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: first Gregorian day of each Bikram Sambat month as printed; generated by tools/nepal/nta_month_starts.py "
        "from the downloaded reports (URL and SHA-256 per row); reports are cited, not stored",
        "bs_year,month,first_day,source_url,source_sha256",
    ]
    return "\n".join(header + rows(directory)) + "\n"


def main() -> None:
    directory = pathlib.Path(sys.argv[1])
    text = render(directory)
    if "--check" in sys.argv:
        if GOLDEN.read_text() != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date")
        print("up to date")
        return
    GOLDEN.write_text(text)
    print(f"{len(text.splitlines()) - 6} rows written")


if __name__ == "__main__":
    main()
