#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Generates the T-1214 launcher day icons and their activity aliases (ADR-0022).

For every day 1..31 this writes an adaptive icon (mipmap-anydpi/ic_launcher_day_NN.xml) whose foreground is the
Taqvim calendar page with the day number drawn inside it: Latin digits in drawable/ and Persian digits in drawable-fa/
(the launcher resolves resources with the system locale). The digits are stroked paths designed for Taqvim on a
10 x 20 grid. It also rewrites the day aliases between the markers in app/src/main/AndroidManifest.xml.

Run from anywhere: python3 tools/icons/launcher_day_icons.py
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
RES = ROOT / "app" / "src" / "main" / "res"
MANIFEST = ROOT / "app" / "src" / "main" / "AndroidManifest.xml"
DAYS = 31
GLYPH_WIDTH = 10.0
GLYPH_GAP = 4.0
GLYPH_TOP = 47.0
CENTER_X = 54.0
STROKE = 3.2

# The calendar page of ic_launcher_foreground.xml, with the whole area below its binding strip left open.
PAGE = "M36,34h36a4,4 0,0 1,4 4v32a4,4 0,0 1,-4 4h-36a4,4 0,0 1,-4 -4v-32a4,4 0,0 1,4 -4zM36,44v26h36v-26z"

LATIN = {
    "0": "M5,0 A5,10 0 1 1 5,20 A5,10 0 1 1 5,0",
    "1": "M1.5,4.5 L6,0 L6,20",
    "2": "M0.5,5 A4.5,4.5 0 1 1 8.2,8.2 L0,20 L10,20",
    "3": "M0.5,1 L9.5,1 L4.5,8 A6,6 0 1 1 0.5,18",
    "4": "M7,20 L7,0 L0,14 L10,14",
    "5": "M9.5,0 L1.5,0 L0.5,8.5 A6,6 0 1 1 0.5,18.5",
    "6": "M8.5,0.5 L1.5,11 M0,15 A5,5 0 1 0 10,15 A5,5 0 1 0 0,15",
    "7": "M0,0 L10,0 L3.5,20",
    "8": "M5,0.5 A4.5,4.5 0 1 0 5,9.5 A4.5,4.5 0 1 0 5,0.5 M5,9.5 A5.25,5.25 0 1 0 5,20 A5.25,5.25 0 1 0 5,9.5",
    "9": "M10,5 A5,5 0 1 0 0,5 A5,5 0 1 0 10,5 L6.5,20",
}

PERSIAN = {
    "0": "M4,10 L6,10",
    "1": "M4,1 Q6,10 5,20",
    "2": "M2,1 Q2,12 3,20 M2.5,6 Q8,7 9,0",
    "3": "M1.5,1 Q1.5,12 2.5,20 M2,6 Q5,7 5.5,1 Q6,7 9.5,0",
    "4": "M9.5,1 Q3,0 3,5 Q3.5,8.5 8.5,8 Q2,9 2.5,13.5 Q3,20 5,20",
    "5": "M5,5 Q-0.5,13 3,19 Q5,21 7,19 Q10.5,13 5,5 Z",
    "6": "M1.5,1.5 Q3,6 9,4.5 M9,4.5 Q6,12 3,20",
    "7": "M0.5,0 L5,20 L9.5,0",
    "8": "M0.5,20 L5,0 L9.5,20",
    "9": "M5,1 A4,4 0 1 0 5,9 A4,4 0 1 0 5,1 M8.8,5 Q9,12 7.5,20",
}

# Number of arguments of each path command and which of them are x/y coordinates to move.
COMMANDS = {"M": (2, (0,)), "L": (2, (0,)), "Q": (4, (0, 2)), "A": (7, (5,)), "Z": (0, ())}


def fmt(value):
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return "0" if text == "-0" else text


def moved(path, dx, dy):
    """[path] translated by (dx, dy)."""
    tokens = re.findall(r"[MLQAZ]|-?\d+(?:\.\d+)?", path)
    out = []
    index = 0
    while index < len(tokens):
        command = tokens[index]
        count, points = COMMANDS[command]
        args = [float(token) for token in tokens[index + 1:index + 1 + count]]
        for point in points:
            args[point] += dx
            args[point + 1] += dy
        out.append(command + ",".join(fmt(arg) for arg in args) if args else command)
        index += 1 + count
    return " ".join(out)


def digits_path(number, glyphs):
    text = str(number)
    width = len(text) * GLYPH_WIDTH + (len(text) - 1) * GLYPH_GAP
    left = CENTER_X - width / 2
    return " ".join(
        moved(glyphs[digit], left + position * (GLYPH_WIDTH + GLYPH_GAP), GLYPH_TOP)
        for position, digit in enumerate(text)
    )


def foreground(number, glyphs, script):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- T-1214 (ADR-0022): the Taqvim calendar page showing day {number} in {script} digits.
     Generated by tools/icons/launcher_day_icons.py; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
  android:width="108dp"
  android:height="108dp"
  android:viewportWidth="108"
  android:viewportHeight="108">
  <path
    android:fillColor="@color/launcher_foreground"
    android:pathData="{PAGE}" />
  <path
    android:pathData="{digits_path(number, glyphs)}"
    android:strokeColor="@color/launcher_foreground"
    android:strokeLineCap="round"
    android:strokeLineJoin="round"
    android:strokeWidth="{fmt(STROKE)}" />
</vector>
"""


def adaptive(name):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- T-1214 (ADR-0022). Generated by tools/icons/launcher_day_icons.py; do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/launcher_background" />
  <foreground android:drawable="@drawable/{name}" />
  <monochrome android:drawable="@drawable/{name}" />
</adaptive-icon>
"""


def aliases():
    blocks = []
    for day in range(1, DAYS + 1):
        name = f"ic_launcher_day_{day:02d}"
        blocks.append(f"""    <activity-alias
      android:name=".LauncherDay{day:02d}"
      android:enabled="false"
      android:exported="true"
      android:icon="@mipmap/{name}"
      android:roundIcon="@mipmap/{name}"
      android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>""")
    return "\n".join(blocks)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main():
    for day in range(1, DAYS + 1):
        name = f"ic_launcher_day_{day:02d}"
        write(RES / "drawable" / f"{name}.xml", foreground(day, LATIN, "Latin"))
        write(RES / "drawable-fa" / f"{name}.xml", foreground(day, PERSIAN, "Persian"))
        write(RES / "mipmap-anydpi" / f"{name}.xml", adaptive(name))
    manifest = MANIFEST.read_text(encoding="utf-8")
    begin = "    <!-- launcher-day-aliases:begin (generated by tools/icons/launcher_day_icons.py) -->\n"
    end = "    <!-- launcher-day-aliases:end -->"
    start = manifest.index(begin) + len(begin)
    stop = manifest.index(end)
    MANIFEST.write_text(manifest[:start] + aliases() + "\n" + manifest[stop:], encoding="utf-8")


if __name__ == "__main__":
    main()
