import com.android.build.api.artifact.SingleArtifact
import com.android.build.api.variant.BuiltArtifactsLoader
import ir.taqvim.buildlogic.ApkNativeLibraries
import ir.taqvim.buildlogic.ApkSizeBudget
import ir.taqvim.buildlogic.ApkSizeStatus
import ir.taqvim.buildlogic.BaselineProfileRules
import ir.taqvim.buildlogic.PageAlignment
import ir.taqvim.buildlogic.TaqvimVersion
import javax.xml.parsers.DocumentBuilderFactory

plugins {
    alias(libs.plugins.taqvim.android.application)
    alias(libs.plugins.taqvim.android.compose)
    // Serializable navigation destinations, saved with the back stack (ADR-0015).
    id("org.jetbrains.kotlin.plugin.serialization")
    // T-1800 (ADR-0018): consumes the baseline and startup profiles generated by :benchmark.
    id("androidx.baselineprofile")
}

/** Gradle Managed Device for the device smoke tests: `./gradlew :app:pixel6Api34DebugAndroidTest` (docs/RELEASE.md). */
val smokeDevice = "pixel6Api34"

/** Plan §9: release APK at most 8 MB; the build warns from 90 % of it (T-1800). */
val apkBudgetBytes: Long = ApkSizeBudget.BUDGET_BYTES

/** The release tag passed by CI (`-Ptaqvim.version`), otherwise the checked-in `version.properties` (T-1900). */
val taqvimVersion: TaqvimVersion =
    TaqvimVersion.resolve(
        property = providers.gradleProperty(TaqvimVersion.PROPERTY).orNull,
        propertiesFile =
            providers
                .fileContents(rootProject.layout.projectDirectory.file("version.properties"))
                .asText
                .orNull,
    )

/**
 * T-1800: the locale qualifiers kept in the resource table, one per launch language of
 * `app/src/main/res/xml/locales_config.xml`, plus the older qualifier spelling that libraries use for the same
 * language so their translations survive the filter.
 */
val launchLocaleFilters =
    setOf(
        "en",
        "ar",
        "b+az+Latn",
        "az",
        "b+ckb",
        "ckb",
        "b+uz+Latn",
        "uz",
        "b+zh+Hans",
        "zh",
        "zh-rCN",
        "bn",
        "de",
        "es",
        "fa",
        "fa-rAF",
        "fr",
        "hi",
        "in",
        "ja",
        "ku",
        "ms",
        "ne",
        "ps",
        "ru",
        "ta",
        "tg",
        "tr",
        "ur",
        // Debug pseudo-locales (isPseudoLocalesEnabled): the filter would otherwise drop them. Release builds never
        // generate them, so they cost nothing there.
        "en-rXA",
        "ar-rXB",
    )

android {
    namespace = "ir.taqvim.app"
    defaultConfig {
        applicationId = "ir.taqvim.app"
        versionCode = taqvimVersion.code
        versionName = taqvimVersion.name
        // A device test that hangs (e.g. a screen that never becomes idle) fails after 10 minutes instead of stalling.
        testInstrumentationRunnerArguments["timeout_msec"] = "600000"
    }
    buildFeatures {
        // Version and build type shown on the About screen and in problem reports (T-1504).
        buildConfig = true
    }
    signingConfigs {
        // Release signing comes from CI secrets (release.yml). Without them release builds stay unsigned.
        val keystore = providers.environmentVariable("TAQVIM_KEYSTORE_FILE").orNull
        if (keystore != null) {
            create("release") {
                storeFile = file(keystore)
                storePassword = providers.environmentVariable("TAQVIM_KEYSTORE_PASSWORD").get()
                keyAlias = providers.environmentVariable("TAQVIM_KEY_ALIAS").get()
                keyPassword = providers.environmentVariable("TAQVIM_KEY_PASSWORD").get()
            }
        }
    }
    buildTypes {
        getByName("debug") {
            // en-XA (accented, expanded) and ar-XB (mirrored RTL) pseudo-locales catch untranslated or clipped text.
            isPseudoLocalesEnabled = true
        }
        getByName("release") {
            signingConfig = signingConfigs.findByName("release")
        }
        create("benchmark") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += listOf("release")
            isDebuggable = false
        }
    }
    testOptions {
        managedDevices {
            localDevices {
                create(smokeDevice) {
                    device = "Pixel 6"
                    apiLevel = 34
                    systemImageSource = "aosp-atd"
                }
            }
        }
    }
    bundle {
        // The app language is chosen in the app (T-1501, ADR-0023), so every language's resources must be installed.
        language {
            enableSplit = false
        }
    }
    androidResources {
        // T-1800 (ADR-0018 addendum): keep only the 24 launch languages of locales_config.xml. Libraries such as
        // appcompat ship strings for about ninety locales; the rest cost about 6 kB of resource table each and are
        // unreachable, because the language picker (T-1501) offers exactly these locales. Kept equal to
        // LanguageTable by AppLocalesTest; the plain codes next to the BCP-47 ones keep the library translations
        // that use the older qualifier (values-zh-rCN for b+zh+Hans, values-az for b+az+Latn).
        localeFilters += launchLocaleFilters
    }
    packaging {
        resources {
            // T-1800: build-time metadata that no code reads at runtime. The Apache-2.0 notices stay available in
            // the About screen, which serves them from assets/licenses (T-1504), not from these META-INF copies.
            excludes +=
                setOf(
                    "**/*.proto",
                    "**/*.proto.bin",
                    "**/*.kotlin_builtins",
                    "DebugProbesKt.bin",
                    "META-INF/*.version",
                    "META-INF/version-control-info.textproto",
                    "META-INF/androidx/**",
                    "META-INF/org/**",
                )
        }
    }
}

baselineProfile {
    // Generated only on request (`./gradlew :app:generateBaselineProfile`), never during a normal build; the
    // reviewed files are committed under src/main/generated/baselineProfiles. Builds work without them.
    automaticGenerationDuringBuild = false
    saveInSrc = true
    mergeIntoMain = true
    // Startup profile packaging and dex layout optimisation (ADR-0018 addendum).
    dexLayoutOptimization = true
}

dependencies {
    implementation(projects.core.model)
    implementation(projects.core.calendar)
    implementation(projects.core.events)
    implementation(projects.core.praytimes)
    implementation(projects.core.astronomy)
    implementation(projects.core.i18n)
    implementation(projects.core.nlp)
    implementation(projects.core.ics)
    implementation(projects.core.workdays)
    implementation(projects.core.ui)

    implementation(projects.data.preferences)
    implementation(projects.data.database)
    implementation(projects.data.events)
    implementation(projects.data.deviceCalendar)
    implementation(projects.data.location)
    implementation(projects.data.scheduler)

    implementation(projects.feature.calendar)
    implementation(projects.feature.timeline)
    implementation(projects.feature.month)
    implementation(projects.feature.year)
    implementation(projects.feature.agenda)
    implementation(projects.feature.events)
    implementation(projects.feature.times)
    implementation(projects.feature.astronomy)
    implementation(projects.feature.map)
    implementation(projects.feature.compass)
    implementation(projects.feature.tools)
    implementation(projects.feature.settings)
    implementation(projects.feature.about)
    implementation(projects.feature.widgets)
    implementation(projects.feature.notification)
    implementation(projects.feature.wallpaper)
    implementation(projects.feature.search)
    implementation(projects.feature.backup)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.profileinstaller)
    // Profiles come from BaselineProfileGenerator on a Gradle Managed Device (T-1800).
    baselineProfile(projects.benchmark)
    implementation(platform(libs.koin.bom))
    implementation(libs.koin.android)
    implementation(libs.koin.androidx.compose)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.androidx.compose.material3.adaptive.navigation.suite)
    implementation(libs.androidx.browser)
    // LevelCalibration (T-1303) exposes an ImmutableMap in the compass port; stored by the T-1500 adapters.
    implementation(libs.kotlinx.collections.immutable)

    // Plan T-1803: leak detection in debug builds only (ADR-0021); never in release.
    debugImplementation(libs.leakcanary.android)

    testImplementation(libs.koin.test)
    // Screenshot environments of the navigation frame (ADR-0015).
    testImplementation(projects.core.uiTesting)
    testImplementation(libs.kotlinx.coroutines.test)

    // Device smoke tests on the managed device (T-1600, T-1700, T-1200): real Android, not Robolectric.
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.uiautomator)
    // Brings the Accessibility Test Framework (Apache-2.0) for DeviceAccessibilityTest.
    androidTestImplementation(libs.androidx.compose.ui.test.junit4.accessibility)
}

/**
 * T-1800 (ADR-0018): the shrunk release keeps what reflection and persisted names need. Each line of
 * `shrinking-requirements.txt` is `kept <class>` (present, may be renamed), `named <class>` (present with its name) or
 * `fields <class>` (present with every field name unchanged), checked against the R8 mapping.
 */
abstract class ReleaseShrinkingCheck : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val mapping: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val requirements: RegularFileProperty

    @TaskAction
    fun verify() {
        val classes = mutableMapOf<String, String>()
        val fields = mutableMapOf<String, MutableList<Pair<String, String>>>()
        var current: String? = null
        mapping.get().asFile.forEachLine { line ->
            val header = Regex("""^(\S+) -> (\S+):$""").matchEntire(line)
            val member = Regex("""^\s+\S+ (\S+) -> (\S+)$""").matchEntire(line)
            when {
                header != null -> {
                    current = header.groupValues[1].also { classes[it] = header.groupValues[2] }
                }

                member != null && '(' !in line -> {
                    val owner = current ?: return@forEachLine
                    fields.getOrPut(owner) { mutableListOf() } += member.groupValues[1] to member.groupValues[2]
                }
            }
        }
        val problems =
            requirements
                .get()
                .asFile
                .readLines()
                .map(String::trim)
                .filterNot { it.isEmpty() || it.startsWith("#") }
                .mapNotNull { line ->
                    val (kind, name) = line.split(' ', limit = 2)
                    when (kind) {
                        "kept" -> {
                            "$name was removed".takeIf { name !in classes }
                        }

                        "named" -> {
                            "$name was renamed or removed".takeIf { classes[name] != name }
                        }

                        "fields" -> {
                            val kept = fields[name].orEmpty()
                            "$name lost field names".takeIf { kept.isEmpty() || kept.any { it.first != it.second } }
                        }

                        else -> {
                            "unknown requirement: $line"
                        }
                    }
                }
        check(problems.isEmpty()) { "Release shrinking requirements not met (T-1800):\n" + problems.joinToString("\n") }
    }
}

/**
 * T-1800 plan §9 budget: every APK of the release variant is at most [budgetBytes] bytes. From [warnAtPercent]
 * of the budget the build warns, so growth is visible before it blocks a release (T-1800, ADR-0018 addendum).
 */
abstract class ApkSizeCheck : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val apkDirectory: DirectoryProperty

    @get:Internal
    abstract val loader: Property<BuiltArtifactsLoader>

    @get:Input
    abstract val budgetBytes: Property<Long>

    @get:Input
    abstract val warnAtPercent: Property<Int>

    @TaskAction
    fun measure() {
        val artifacts = checkNotNull(loader.get().load(apkDirectory.get())) { "No APKs in ${apkDirectory.get()}" }
        val reports =
            artifacts.elements.map { element ->
                val apk = File(element.outputFile)
                ApkSizeBudget.report(
                    name = "APK ${apk.name}",
                    bytes = apk.length(),
                    budgetBytes = budgetBytes.get(),
                    warnAtPercent = warnAtPercent.get(),
                )
            }
        reports.forEach { report ->
            when (report.status) {
                ApkSizeStatus.WITHIN_BUDGET -> logger.lifecycle(report.message)
                ApkSizeStatus.NEAR_BUDGET -> logger.warn("w: ${report.message}")
                ApkSizeStatus.OVER_BUDGET -> logger.error("e: ${report.message}")
            }
        }
        val over = reports.filter { it.status == ApkSizeStatus.OVER_BUDGET }
        check(over.isEmpty()) { over.joinToString(separator = "; ") { it.message } }
    }
}

/**
 * T-1800: every native library of the release APK must be usable on a device with 16 KB memory pages (Android 15 and
 * later ship them; the owner's OnePlus 15 is one). A library that is compressed, not on a page boundary, or built
 * with 4 KB segments cannot be mapped there and the app dies at start with `dlopen failed`. Nothing in the JVM or
 * Robolectric suites can see this, and the emulators here use 4 KB pages, so the build checks the APK itself.
 */
abstract class PageAlignmentCheck : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val apkDirectory: DirectoryProperty

    @get:Internal
    abstract val loader: Property<BuiltArtifactsLoader>

    @TaskAction
    fun verify() {
        val artifacts = checkNotNull(loader.get().load(apkDirectory.get())) { "No APKs in ${apkDirectory.get()}" }
        artifacts.elements.forEach { element ->
            val apk = File(element.outputFile)
            val libraries = ApkNativeLibraries.read(apk.readBytes())
            val problems = PageAlignment.problems(libraries)
            check(problems.isEmpty()) {
                "Native libraries of ${apk.name} are not ready for 16 KB pages:\n" + problems.joinToString("\n")
            }
            logger.lifecycle(
                "${apk.name}: ${libraries.size} native libraries mapped at ${PageAlignment.PAGE_BYTES} bytes",
            )
        }
    }
}

/**
 * T-1800: the variant's merged ART profile must hold the app's own rules, not only the ones the AndroidX libraries
 * bundle. It reads the text AGP merges before R8 renames anything, because the packaged `assets/dexopt/baseline.prof`
 * stores dex indices instead of names and cannot be asked which classes it covers.
 */
abstract class BaselineProfileCheck : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val mergedProfileDirectory: DirectoryProperty

    @get:Input
    abstract val variantName: Property<String>

    @TaskAction
    fun verify() {
        val directory = mergedProfileDirectory.get().asFile
        val profile =
            directory.walkTopDown().firstOrNull { it.isFile && it.name == PROFILE_NAME }
                ?: error(
                    "No $PROFILE_NAME under $directory. AGP has moved the merged ART profile, so the T-1800 check " +
                        "cannot see whether ${variantName.get()} still carries the app's baseline profile.",
                )
        val report = BaselineProfileRules.report(variantName.get(), profile.readLines())
        check(report.isComplete) { report.message }
        logger.lifecycle(report.message)
    }

    private companion object {
        const val PROFILE_NAME = "baseline-prof.txt"
    }
}

/**
 * T-1900 (docs/RELEASE.md): every output of the variant carries the resolved Taqvim version. Also prints it, so
 * `./gradlew :app:verifyReleaseVersion -Ptaqvim.version=<tag>` shows the name and code a tag produces.
 */
abstract class VersionCheck : DefaultTask() {
    @get:Input
    abstract val expectedName: Property<String>

    @get:Input
    abstract val expectedCode: Property<Int>

    @get:Input
    abstract val outputNames: ListProperty<String>

    @get:Input
    abstract val outputCodes: ListProperty<Int>

    @TaskAction
    fun verify() {
        logger.lifecycle("Taqvim version ${expectedName.get()} (versionCode ${expectedCode.get()})")
        check(outputNames.get().isNotEmpty() && outputNames.get().all { it == expectedName.get() }) {
            "versionName ${outputNames.get()} differs from ${expectedName.get()}"
        }
        check(outputCodes.get().all { it == expectedCode.get() }) {
            "versionCode ${outputCodes.get()} differs from ${expectedCode.get()}"
        }
    }
}

/**
 * T-1804 manifest audit (ADR-0017): the release manifest exports exactly the components listed for `all` builds in
 * `src/test/resources/security/exported-components.txt`. The debug manifest is checked by ExportedComponentsTest.
 */
abstract class ExportedComponentsAudit : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val manifest: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val allowlist: RegularFileProperty

    @TaskAction
    fun audit() {
        val android = "http://schemas.android.com/apk/res/android"
        val document =
            DocumentBuilderFactory
                .newInstance()
                .apply { isNamespaceAware = true }
                .newDocumentBuilder()
                .parse(manifest.get().asFile)
        val exported =
            listOf("activity", "activity-alias", "service", "receiver", "provider")
                .flatMap { tag ->
                    val nodes = document.getElementsByTagName(tag)
                    (0 until nodes.length).map { nodes.item(it) as org.w3c.dom.Element }
                }.filter { it.getAttributeNS(android, "exported") == "true" }
                .map { component ->
                    val permission = component.getAttributeNS(android, "permission").ifEmpty { "-" }
                    "${component.getAttributeNS(android, "name")} | $permission"
                }.toSet()
        val allowed =
            allowlist
                .get()
                .asFile
                .readLines()
                .map(String::trim)
                .filterNot { it.isEmpty() || it.startsWith("#") }
                .map { line -> line.split('|').map(String::trim) }
                .filter { it.getOrNull(2) == "all" }
                .map { "${it[0]} | ${it[1]}" }
                .toSet()
        check(exported == allowed) {
            "Exported components differ from the allowlist (T-1804).\n" +
                "Not allowed: ${exported - allowed}\nMissing: ${allowed - exported}"
        }
    }
}

androidComponents {
    // T-1800: the androidx.baselineprofile consumer plugin adds the committed profile
    // (src/main/generated/baselineProfiles) to the variants it manages, which does not include a hand-made build
    // type: `initWith(release)` copies the build-type settings, not the profile source. Every macrobenchmark runs
    // against the benchmark variant, so without this it measured an app compiled from the AndroidX libraries'
    // bundled profiles only — no rule of its own — and a lost or empty profile could not fail the nightly gate.
    onVariants(selector().withBuildType("benchmark")) { variant ->
        variant.sources.baselineProfiles?.addStaticSourceDirectory("src/main/generated/baselineProfiles")
    }
    onVariants { variant ->
        // Both non-debuggable variants: release is what users install, benchmark is what every macrobenchmark runs.
        if (variant.buildType !in setOf("release", "benchmark")) return@onVariants
        val variantName = variant.name.replaceFirstChar(Char::uppercase)
        val merge = "merge${variantName}ArtProfile"
        val check =
            tasks.register<BaselineProfileCheck>("check${variantName}BaselineProfile") {
                group = "verification"
                description = "Checks that the ${variant.name} ART profile holds the app's rules (T-1800)."
                dependsOn(merge)
                mergedProfileDirectory.set(
                    layout.buildDirectory.dir("intermediates/merged_art_profile/${variant.name}"),
                )
                this.variantName.set(variant.name)
            }
        tasks.named("check") { dependsOn(check) }
    }
    onVariants(selector().withBuildType("release")) { variant ->
        val taskName = "audit${variant.name.replaceFirstChar(Char::uppercase)}ExportedComponents"
        val audit =
            tasks.register<ExportedComponentsAudit>(taskName) {
                group = "verification"
                description = "Checks the merged ${variant.name} manifest against the exported-components allowlist."
                manifest.set(variant.artifacts.get(SingleArtifact.MERGED_MANIFEST))
                allowlist.set(layout.projectDirectory.file("src/test/resources/security/exported-components.txt"))
            }
        tasks.named("check") { dependsOn(audit) }

        val variantName = variant.name.replaceFirstChar(Char::uppercase)
        tasks.register<ReleaseShrinkingCheck>("verify${variantName}Shrinking") {
            group = "verification"
            description = "Checks the R8 mapping of ${variant.name} against shrinking-requirements.txt (T-1800)."
            mapping.set(variant.artifacts.get(SingleArtifact.OBFUSCATION_MAPPING_FILE))
            requirements.set(layout.projectDirectory.file("shrinking-requirements.txt"))
        }
        tasks.register<PageAlignmentCheck>("check${variantName}PageAlignment") {
            group = "verification"
            description =
                "Checks that every native library of ${variant.name} can be mapped on a 16 KB page device (T-1800)."
            apkDirectory.set(variant.artifacts.get(SingleArtifact.APK))
            loader.set(variant.artifacts.getBuiltArtifactsLoader())
        }
        tasks.register<ApkSizeCheck>("check${variantName}ApkSize") {
            group = "verification"
            description =
                "Warns from ${ApkSizeBudget.WARN_AT_PERCENT} % of the plan §9 size budget and fails a " +
                "${variant.name} APK over it (T-1800)."
            apkDirectory.set(variant.artifacts.get(SingleArtifact.APK))
            loader.set(variant.artifacts.getBuiltArtifactsLoader())
            budgetBytes.set(apkBudgetBytes)
            warnAtPercent.set(ApkSizeBudget.WARN_AT_PERCENT)
        }
    }
    onVariants { variant ->
        val variantName = variant.name.replaceFirstChar(Char::uppercase)
        tasks.register<VersionCheck>("verify${variantName}Version") {
            group = "verification"
            description = "Checks that ${variant.name} uses the version from -Ptaqvim.version or version.properties."
            expectedName.set(taqvimVersion.name)
            expectedCode.set(taqvimVersion.code)
            variant.outputs.forEach { output ->
                outputNames.add(output.versionName)
                outputCodes.add(output.versionCode)
            }
        }
    }
}
