#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Generates core/astronomy's golden/yallop/yallop-1997-table4.csv (A-06) with the observation facts of Yallop's Table 4.

Usage: tools/crescent/yallop_table4_facts.py [--pdf PATH] [--check]

B. D. Yallop, NAO Technical Note 69 (1997, revised 1998), Table 4 lists 295 crescent observations with the facts of
each (number from the original lists, date, morning or evening, latitude, longitude and Schaefer's coded description
of how the crescent was or was not seen) next to Yallop's own computed columns (conjunction JD, ARCL, ARCV, DAZ, age,
lag, parallax, W', q and his predicted code). Only the facts are written; the computed columns are parsed solely to
check the transcription (q must follow equation 3.6 from the row's ARCV and W') and are then discarded, so the app has
to compute the geometry itself (owner decision 2026-09-15, "facts only, app computes").

The PDF is not stored in the repository: pass --pdf with a local copy, or it is downloaded from URL; either way its
SHA-256 must equal SHA256. Needs `pdftotext` (poppler-utils). --check regenerates in memory and compares.
"""
import argparse
import hashlib
import pathlib
import re
import subprocess
import sys
import tempfile
import urllib.request

REPO = pathlib.Path(__file__).resolve().parents[2]
URL = "https://astronomycenter.net/pdf/yallop_1997.pdf"
SHA256 = "47575cde79a8c0f91ae4fa444798fa55e328e8dd7807f54ec73ce16f201cfba6"
GOLDEN = "core/astronomy/src/test/resources/golden/yallop/yallop-1997-table4.csv"
ROWS = 295
Q_TOLERANCE = 0.035  # ARCV and W' are printed to 0.1 (W' to 0.01 below 1'), which moves q by up to about 0.03.
NUMBER = r"[+-]?\d+(?:\.\d+)?"
ROW = re.compile(
    rf"^\s*(\d+)\s+(\d{{4}})\s+(\d{{1,2}})\s+(\d{{1,2}})\s+([ME])\s+((?:{NUMBER}\s+){{11}})(.*)$"
)
CODE = re.compile(r"[VI](?:\([BFITV]\))?")


def pdf_bytes(path):
    if path:
        data = pathlib.Path(path).read_bytes()
    else:
        with urllib.request.urlopen(URL, timeout=120) as response:
            data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise SystemExit(f"PDF sha256 {digest} is not the reviewed {SHA256}")
    return data


def text_of(data):
    with tempfile.TemporaryDirectory() as tmp:
        pdf = pathlib.Path(tmp) / "tn69.pdf"
        pdf.write_bytes(data)
        return subprocess.run(["pdftotext", "-layout", str(pdf), "-"], check=True, capture_output=True, text=True).stdout


def normalized(line):
    return line.replace("·", ".").replace("−", "-").replace("–", "-")


def rows_of(text):
    rows = []
    for line in map(normalized, text.splitlines()):
        match = ROW.match(line)
        if not match:
            continue
        number, year, month, day, phase, numbers, rest = match.groups()
        values = [float(v) for v in numbers.split()]
        codes = CODE.findall(rest.replace(" ", ""))
        if len(codes) != 2 or CODE.sub("", rest.replace(" ", "")):
            raise SystemExit(f"row {number}: cannot read the two visibility codes from {rest!r}")
        latitude, longitude, arcv, width, q = values[1], values[2], values[4], values[9], values[10]
        predicted = (arcv - (11.8371 - 6.3226 * width + 0.7319 * width**2 - 0.1018 * width**3)) / 10
        if abs(predicted - q) > Q_TOLERANCE:
            raise SystemExit(f"row {number}: printed q {q} does not follow ARCV {arcv} and W' {width}")
        date = f"{int(year):04d}-{int(month):02d}-{int(day):02d}"
        rows.append((int(number), date, phase, f"{latitude:.1f}", f"{longitude:.1f}", codes[0]))
    return rows


def unique_rows(rows):
    """Table 4 rows once each: the note repeats 50 of them word for word in later tables, which must not differ."""
    first = {}
    for row in rows:
        if first.setdefault(row[0], row) != row:
            raise SystemExit(f"observation {row[0]} is printed twice with different facts: {first[row[0]]} / {row}")
    return list(first.values())


def golden_text(rows):
    numbers = [row[0] for row in rows]
    if len(rows) != ROWS or len(set(numbers)) != ROWS:
        raise SystemExit(f"expected {ROWS} distinct observations, read {len(rows)} ({len(set(numbers))} distinct)")
    header = [
        '# source: B. D. Yallop, "A Method for Predicting the First Sighting of the New Crescent Moon", NAO Technical '
        "Note No. 69, HM Nautical Almanac Office (1997, revised 1998), Table 4: the observation facts of its 295 "
        "observations",
        f"# url: {URL}",
        "# retrieved: 2026-09-13",
        "# page: 5-10",
        "# reviewer: pending",
        f"# notes: PDF sha256={SHA256} (not stored); generated by tools/crescent/yallop_table4_facts.py from "
        "pdftotext -layout; facts only (owner decision 2026-09-15): number from the original lists, date as printed "
        "(year, month, day), M(orning)/E(vening), latitude and east longitude in degrees, and Schaefer's coded "
        "description of the sighting (column 17: V seen or I not seen with the unaided eye; (F) optical aid used to "
        "find it, (B)/(T)/(V) seen and (I) not seen with binoculars or a telescope); Yallop's computed columns "
        "(conjunction JD, ARCL, ARCV, DAZ, age, lag, parallax, W', q, predicted code and group) are checked against "
        "equation 3.6 and not stored; rows in the table's order of decreasing q",
        "no,date,m_or_e,latitude,longitude,observation",
    ]
    return "\n".join(header + [",".join(str(v) for v in row) for row in rows]) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = golden_text(unique_rows(rows_of(text_of(pdf_bytes(args.pdf)))))
    target = REPO / GOLDEN
    if args.check:
        if target.read_text() != text:
            sys.exit(f"{GOLDEN} is out of date; rerun tools/crescent/yallop_table4_facts.py")
        print(f"{GOLDEN} is up to date")
        return
    target.write_text(text)
    print(f"{ROWS} rows written to {GOLDEN}")


if __name__ == "__main__":
    main()
