/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.calendar

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.comparables.shouldBeGreaterThanOrEqualTo
import io.kotest.matchers.comparables.shouldBeLessThanOrEqualTo
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.property.Arb
import io.kotest.property.arbitrary.int
import io.kotest.property.checkAll
import ir.taqvim.core.model.CalendarDate
import ir.taqvim.core.model.CalendarSystem
import ir.taqvim.core.model.Weekday
import ir.taqvim.core.testing.GoldenFile
import ir.taqvim.core.testing.PropertyTesting
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test

/**
 * T-109 Gregorian Easter and movable feasts against every observance the U.S. Naval Observatory publishes for the
 * Gregorian years 1583-9999 (golden/usno, generated by tools/usno/usno_christian_observances.py).
 */
class ChristianMovableFeastsTest {
    private val rows =
        GoldenFile
            .load("golden/usno/christian-observances-1583-9999.csv")
            .lines
            .drop(1)
            .map { it.split(',') }

    private fun date(
        year: Int,
        month: Int,
        day: Int,
    ) = CalendarDate(CalendarSystem.GREGORIAN, year, month, day)

    @Test
    fun `the golden holds every USNO year from 1583 to 9999`() {
        rows shouldHaveSize LAST_YEAR - GregorianComputus.FIRST_YEAR + 1
        rows.map { it.first().toInt() } shouldBe (GregorianComputus.FIRST_YEAR..LAST_YEAR).toList()
        rows.filterNot { it.size == MovableFeast.entries.size + 1 }.shouldBeEmpty()
    }

    @Test
    fun `every published observance matches`() {
        rows
            .flatMap { row ->
                val feasts = ChristianMovableFeasts.forYear(row.first().toInt())
                MovableFeast.entries.mapIndexedNotNull { index, feast ->
                    val published = row[index + 1]
                    "${row.first()} $feast: published $published".takeIf { feasts.getValue(feast).iso() != published }
                }
            }.shouldBeEmpty()
    }

    @Test
    fun `Easter matches the examples and extremes Meeus lists`() {
        // Meeus, Astronomical Algorithms (2nd ed.), ch. 8.
        GregorianComputus.easter(1991) shouldBe date(1991, 3, 31)
        GregorianComputus.easter(1992) shouldBe date(1992, 4, 19)
        GregorianComputus.easter(1993) shouldBe date(1993, 4, 11)
        GregorianComputus.easter(1954) shouldBe date(1954, 4, 18)
        GregorianComputus.easter(2000) shouldBe date(2000, 4, 23)
        GregorianComputus.easter(1818) shouldBe date(1818, 3, 22)
        GregorianComputus.easter(2285) shouldBe date(2285, 3, 22)
        GregorianComputus.easter(2038) shouldBe date(2038, 4, 25)
        GregorianComputus.easter(GregorianComputus.FIRST_YEAR) shouldBe date(1583, 4, 10)
    }

    @Test
    fun `feasts keep their weekdays and windows up to ten million`(): Unit =
        runBlocking {
            checkAll(PropertyTesting.iterations, Arb.int(GregorianComputus.FIRST_YEAR..TEN_MILLION)) { year ->
                assertFeastRules(year)
            }
        }

    @Test
    fun `feasts keep their weekdays and windows across the whole year range`(): Unit =
        runBlocking {
            checkAll(PropertyTesting.iterations, Arb.int(GregorianComputus.FIRST_YEAR..GregorianComputus.LAST_YEAR)) {
                assertFeastRules(it)
            }
            (GregorianComputus.LAST_YEAR - NEAR_LIMIT..GregorianComputus.LAST_YEAR).forEach(::assertFeastRules)
        }

    @Test
    fun `Easter dates repeat every 5 700 000 years`(): Unit =
        runBlocking {
            val lastStart = GregorianComputus.LAST_YEAR - GregorianComputus.CYCLE_YEARS
            checkAll(PropertyTesting.iterations, Arb.int(GregorianComputus.FIRST_YEAR..lastStart)) { year ->
                val later = GregorianComputus.easter(year + GregorianComputus.CYCLE_YEARS)
                later.monthDay() shouldBe GregorianComputus.easter(year).monthDay()
            }
            GregorianComputus.easter(GregorianComputus.FIRST_YEAR + GregorianComputus.CYCLE_YEARS).monthDay() shouldBe
                GregorianComputus.easter(GregorianComputus.FIRST_YEAR).monthDay()
            GregorianComputus.easter(GregorianComputus.LAST_YEAR) shouldBe date(GregorianComputus.LAST_YEAR, 4, 14)
        }

    private fun assertFeastRules(year: Int) {
        val feasts = ChristianMovableFeasts.forYear(year)
        val easter = feasts.getValue(MovableFeast.EASTER)
        easter shouldBe GregorianComputus.easter(year)
        easter.weekday() shouldBe Weekday.SUNDAY
        easter.monthDay() shouldBeGreaterThanOrEqualTo EARLIEST_EASTER
        easter.monthDay() shouldBeLessThanOrEqualTo LATEST_EASTER
        val advent = feasts.getValue(MovableFeast.FIRST_SUNDAY_OF_ADVENT)
        advent.weekday() shouldBe Weekday.SUNDAY
        advent.monthDay() shouldBeGreaterThanOrEqualTo EARLIEST_ADVENT
        advent.monthDay() shouldBeLessThanOrEqualTo LATEST_ADVENT
        MovableFeast.entries.forEach { feast ->
            feast.daysFromEaster?.let { offset -> feasts.getValue(feast).jdn() - easter.jdn() shouldBe offset.toLong() }
        }
        feasts.values.map { it.jdn() } shouldBe feasts.values.map { it.jdn() }.sorted()
        feasts.values.map { it.year }.distinct() shouldBe listOf(year)
    }

    @Test
    fun `years before the Gregorian computus are rejected`() {
        shouldThrow<IllegalArgumentException> { GregorianComputus.easter(1_582) }.message.orEmpty() shouldContain
            "1582"
        shouldThrow<IllegalArgumentException> { ChristianMovableFeasts.forYear(-1) }
        ChristianMovableFeasts.firstSundayOfAdvent(1_582) shouldBe date(1582, 11, 28)
    }

    private fun CalendarDate.jdn() = GregorianCalendarSystem.toJdn(this)

    private fun CalendarDate.weekday() = jdn().weekday()

    private fun CalendarDate.monthDay() = month * MONTH_DAY_SCALE + day

    private fun CalendarDate.iso() = "%04d-%02d-%02d".format(year, month, day)

    private companion object {
        const val LAST_YEAR = 9_999
        const val TEN_MILLION = 10_000_000
        const val NEAR_LIMIT = 1_000
        const val MONTH_DAY_SCALE = 100
        const val EARLIEST_EASTER = 322
        const val LATEST_EASTER = 425
        const val EARLIEST_ADVENT = 1_127
        const val LATEST_ADVENT = 1_203
    }
}
