/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.calendar

import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import ir.taqvim.core.model.CalendarDate
import ir.taqvim.core.model.CalendarSystem
import ir.taqvim.core.testing.GoldenFile
import kotlinx.datetime.DatePeriod
import kotlinx.datetime.LocalDate
import kotlinx.datetime.plus
import org.junit.jupiter.api.Test

/**
 * A-07 against the month ranges the Nepal Telecommunications Authority prints on its monthly reports, BS 2070–2078
 * (golden/nepal, generated by tools/nepal/nta_month_starts.py).
 */
class NtaNepaliMonthStartsTest {
    private val rows =
        GoldenFile
            .load("golden/nepal/nta-month-starts.csv")
            .lines
            .drop(1)
            .map { it.split(',') }

    /**
     * Rows the computed calendar does not reproduce, each checked below. Four contradict the next or previous report of
     * the same authority, or misprint the year; one has its sankranti within a minute of midnight.
     */
    private val explained =
        mapOf(
            // Kumbha 2073 at 00:01 NPT on 13 February 2017, closer to midnight than the model's accuracy.
            (2073 to 11) to DatePeriod(days = 1),
            // The Chaitra 2074 report ends that month on 13 April 2018, so Baisakh 2075 began on 14 April.
            (2075 to 1) to DatePeriod(days = 1),
            // The Mangsir 2076 report ends that month on 16 December 2019, so Poush began on 17 December.
            (2076 to 9) to DatePeriod(days = 1),
            // The Ashad 2077 report ends that month on 15 July 2020, so Shrawan began on 16 July.
            (2077 to 4) to DatePeriod(days = 1),
            // Printed as 15 January 2021 for Magh 2078, a month of 2022.
            (2078 to 10) to DatePeriod(years = 1),
        )

    @Test
    fun `the golden holds the reports of BS 2070 to 2078`() {
        rows shouldHaveSize REPORTS
        rows.map { it[YEAR].toInt() }.toSet() shouldBe (2070..2078).toSet()
    }

    @Test
    fun `every printed month start is computed except the explained rows`() {
        rows.forEach { row ->
            val key = row[YEAR].toInt() to row[MONTH].toInt()
            val printed = LocalDate.parse(row[FIRST_DAY])
            val expected = explained[key]?.let { printed.plus(it) } ?: printed
            NepaliCalendarSystem.toJdn(CalendarDate(CalendarSystem.NEPALI, key.first, key.second, 1)) shouldBe
                expected.toJdn()
        }
    }

    private companion object {
        const val YEAR = 0
        const val MONTH = 1
        const val FIRST_DAY = 2
        const val REPORTS = 89
    }
}
