/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.calendar

import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import ir.taqvim.core.model.CalendarDate
import ir.taqvim.core.model.CalendarSystem
import ir.taqvim.core.model.Jdn
import ir.taqvim.core.testing.GoldenFile
import org.junit.jupiter.api.Test

/**
 * A-03 type II against every Islamic New Year, 1 Ramadan and 1 Shawwal the U.S. Naval Observatory publishes for the
 * Gregorian years 622-9999 (golden/usno, generated by tools/usno/usno_islamic_observances.py).
 */
class UsnoIslamicObservancesTest {
    /** A first day of a Hijri month and the civil date USNO gives for it. */
    private data class MonthStart(
        val hijriYear: Int,
        val month: Int,
        val civilDate: String,
    ) {
        val hijri: CalendarDate
            get() = CalendarDate(CalendarSystem.ISLAMIC, hijriYear, month, 1)
    }

    private val rows =
        GoldenFile
            .load("golden/usno/islamic-observances-622-9999.csv")
            .lines
            .drop(1)
            .map { it.split(',') }

    private val starts =
        rows.flatMap { row ->
            MONTH_COLUMNS.mapNotNull { (column, month) ->
                row[column].takeIf { it.isNotEmpty() }?.let { MonthStart(row[YEAR].toInt(), month, it) }
            }
        }

    @Test
    fun `the golden holds every USNO record for Hijri years 1 to 9666`() {
        rows shouldHaveSize LAST_HIJRI_YEAR
        rows.map { it[YEAR].toInt() } shouldBe (1..LAST_HIJRI_YEAR).toList()
        starts shouldHaveSize RECORDS
    }

    @Test
    fun `civil dates switch from Julian to Gregorian at the 1582 reform`() {
        civilJdn("1582-10-04").value + 1 shouldBe civilJdn("1582-10-15").value
        civilJdn("0622-07-16") shouldBe Jdn(TabularIslamicCalendar.EPOCH_JDN)
        civilJdn("2000-01-01") shouldBe Jdn(J2000_JDN)
    }

    @Test
    fun `type II gives every published month start`() {
        val typeII = TabularIslamicCalendar.TYPE_II
        starts
            .filterNot { start ->
                val jdn = civilJdn(start.civilDate)
                typeII.toJdn(start.hijri) == jdn && typeII.fromJdn(jdn) == start.hijri
            }.shouldBeEmpty()
    }

    @Test
    fun `type I is one day later exactly in cycle year 16`() {
        val typeI = TabularIslamicCalendar.TYPE_I
        val differing = starts.filter { typeI.toJdn(it.hijri) != civilJdn(it.civilDate) }
        differing shouldBe starts.filter { Math.floorMod(it.hijriYear - 1, CYCLE) + 1 == LEAP_YEAR_OF_TYPE_II_ONLY }
        differing.filterNot { typeI.toJdn(it.hijri).value - civilJdn(it.civilDate).value == 1L }.shouldBeEmpty()
    }

    /** JDN of an ISO-like civil date: Julian before 1582-10-15 (as USNO prints it), proleptic Gregorian from then on. */
    private fun civilJdn(iso: String): Jdn {
        val (year, month, day) = iso.split('-').map(String::toInt)
        return if (iso < FIRST_GREGORIAN_DAY) {
            Jdn(julianToJdn(year, month, day))
        } else {
            GregorianCalendarSystem.toJdn(CalendarDate(CalendarSystem.GREGORIAN, year, month, day))
        }
    }

    /**
     * Julian-calendar date to JDN for positive years, by the integer month-shift algorithm (E. G. Richards,
     * "Calendars", Explanatory Supplement to the Astronomical Almanac, 3rd ed., §15.11).
     */
    private fun julianToJdn(
        year: Int,
        month: Int,
        day: Int,
    ): Long {
        val shift = (14 - month) / 12
        val shiftedYear = year + 4_800L - shift
        val shiftedMonth = month + 12 * shift - 3
        return day + (153 * shiftedMonth + 2) / 5 + 365 * shiftedYear + shiftedYear / 4 - 32_083
    }

    private companion object {
        const val YEAR = 0
        val MONTH_COLUMNS = listOf(1 to 1, 2 to 9, 3 to 10)
        const val LAST_HIJRI_YEAR = 9_666
        const val RECORDS = 28_996
        const val FIRST_GREGORIAN_DAY = "1582-10-15"
        const val J2000_JDN = 2_451_545L
        const val CYCLE = 30
        const val LEAP_YEAR_OF_TYPE_II_ONLY = 16
    }
}
