/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.calendar

import io.kotest.common.ExperimentalKotest
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import io.kotest.property.Arb
import io.kotest.property.PropTestConfig
import io.kotest.property.arbitrary.int
import io.kotest.property.checkAll
import ir.taqvim.core.model.Jdn
import ir.taqvim.core.testing.GoldenFile
import ir.taqvim.core.testing.PropertyTesting
import kotlin.time.Duration.Companion.seconds
import kotlin.time.Instant
import kotlinx.coroutines.runBlocking
import kotlinx.datetime.DateTimeUnit
import kotlinx.datetime.LocalDate
import kotlinx.datetime.TimeZone
import kotlinx.datetime.UtcOffset
import kotlinx.datetime.atStartOfDayIn
import kotlinx.datetime.offsetIn
import kotlinx.datetime.plus
import org.junit.jupiter.api.Test

/** Columns of `golden/usno/us-daylight-saving-1967-9999.csv`. */
private const val YEAR = 0
private const val BEGINS = 1
private const val ENDS = 2

private const val SECONDS_PER_DAY = 86_400L
private const val SECONDS_PER_HOUR = 3_600

/** 17:00 UT is 09:00–13:00 local in the four zones: after their 02:00 local change and before the next local day. */
private const val PROBE_SECOND_OF_DAY = 17L * SECONDS_PER_HOUR

/**
 * T-110: the time zones behind [toJdn] — kotlinx.datetime over the JVM's bundled tz database — against every US
 * daylight saving begin and end date the U.S. Naval Observatory publishes for 1967–9999 (golden/usno, generated by
 * tools/usno/usno_us_daylight_saving.py). New York, Chicago, Denver and Los Angeles follow the national dates in every
 * one of those years, including the 1974 and 1975 energy-crisis starts and the 2007 rule projected to 9999. On a
 * device the tz database is the platform's own copy, so this checks the rules and the bridge, not a specific device.
 */
class UsnoUsDaylightSavingTest {
    /**
     * Fixed seed: the same inputs, and so the same covered branches, on every run and machine. The opt-in is for
     * `iterations`, which Kotest 6 still marks experimental.
     */
    @OptIn(ExperimentalKotest::class)
    private val propertyConfig = PropTestConfig(seed = 20_260_920L, iterations = PropertyTesting.iterations)

    /** The dates USNO gives for one year. */
    private data class UsnoYear(
        val year: Int,
        val begins: LocalDate,
        val ends: LocalDate,
    )

    /** A civil day on which [zone]'s UTC offset differs from the day before, and the new [offset]. */
    private data class OffsetChange(
        val date: LocalDate,
        val offset: UtcOffset,
    )

    /** A contiguous-US zone that observes daylight saving time, with its standard offset. */
    private data class UsZone(
        val zone: TimeZone,
        val standard: UtcOffset,
    ) {
        val daylight: UtcOffset
            get() = UtcOffset(seconds = standard.totalSeconds + SECONDS_PER_HOUR)
    }

    private val usno =
        GoldenFile
            .load("golden/usno/us-daylight-saving-1967-9999.csv")
            .lines
            .drop(1)
            .map { it.split(',') }
            .map { row -> UsnoYear(row[YEAR].toInt(), LocalDate.parse(row[BEGINS]), LocalDate.parse(row[ENDS])) }

    private val zones =
        listOf(
            UsZone(TimeZone.of("America/New_York"), UtcOffset(hours = -5)),
            UsZone(TimeZone.of("America/Chicago"), UtcOffset(hours = -6)),
            UsZone(TimeZone.of("America/Denver"), UtcOffset(hours = -7)),
            UsZone(TimeZone.of("America/Los_Angeles"), UtcOffset(hours = -8)),
        )

    @Test
    fun `the golden holds a begin and an end date for every year from 1967 to 9999`() {
        usno.map { it.year } shouldBe (1967..9999).toList()
        usno.filterNot { it.begins.year == it.year && it.ends.year == it.year && it.begins < it.ends }.shouldBeEmpty()
    }

    @Test
    fun `US zones change to and from daylight time only on the USNO dates`() {
        zones.forEach { usZone ->
            val changes = offsetChanges(usZone.zone).groupBy { it.date.year }
            usno
                .map { it to changes[it.year].orEmpty() }
                .filterNot { (year, found) ->
                    found ==
                        listOf(OffsetChange(year.begins, usZone.daylight), OffsetChange(year.ends, usZone.standard))
                }.map { (year, found) -> "${usZone.zone}: USNO $year, tz database $found" }
                .shouldBeEmpty()
        }
    }

    @Test
    fun `civil days are 23 hours on USNO begin dates and 25 hours on end dates`() {
        zones.forEach { usZone ->
            usno
                .filterNot { year ->
                    civilDayMatches(usZone.zone, year.begins, usZone.standard, usZone.daylight) &&
                        civilDayMatches(usZone.zone, year.ends, usZone.daylight, usZone.standard)
                }.map { "${usZone.zone}: $it" }
                .shouldBeEmpty()
        }
    }

    @Test
    fun `the tz database follows the national rule beyond the USNO range`(): Unit =
        runBlocking {
            checkAll(propertyConfig, Arb.int(10_000..10_000_000)) { year ->
                assertFollowsNationalRule(year)
            }
        }

    @Test
    fun `the year right after the USNO golden's range still follows the national rule`() {
        // The golden (checked above) only covers 1967..9999; 10 000 is the literal lower bound the property above
        // draws from, and a fixed seed no longer guarantees hitting it by chance, so it is pinned here directly.
        assertFollowsNationalRule(10_000)
    }

    private fun assertFollowsNationalRule(year: Int) {
        val dates = UsDaylightSavingRules.forYear(year.toLong()).shouldNotBeNull()
        zones.forEach { usZone ->
            listOf(
                offsetsAround(usZone.zone, year, dates.begins) to (usZone.standard to usZone.daylight),
                offsetsAround(usZone.zone, year, dates.ends) to (usZone.daylight to usZone.standard),
            ).filterNot { (found, expected) -> found == expected }
                .map { "${usZone.zone} $year: $it" }
                .shouldBeEmpty()
        }
    }

    /** The 17:00 UT offsets in [zone] on the day before [day] of [year] and on that day. */
    private fun offsetsAround(
        zone: TimeZone,
        year: Int,
        day: GregorianMonthDay,
    ): Pair<UtcOffset, UtcOffset> {
        val epochDay = LocalDate(year, day.month, day.day).toEpochDays()
        return probe(epochDay - 1).offsetIn(zone) to probe(epochDay).offsetIn(zone)
    }

    /** Every day from 1967 to 9999 whose 17:00 UT offset in [zone] differs from the previous day's. */
    private fun offsetChanges(zone: TimeZone): List<OffsetChange> {
        val first = LocalDate(1967, 1, 1).toEpochDays()
        val last = LocalDate(9999, 12, 31).toEpochDays()
        var previous = probe(first - 1).offsetIn(zone)
        return (first..last).mapNotNull { day ->
            val offset = probe(day).offsetIn(zone)
            OffsetChange(LocalDate.fromEpochDays(day), offset).takeIf { offset != previous }.also { previous = offset }
        }
    }

    /**
     * Whether [date] starts at local midnight under [startOffset] and ends at the next local midnight under
     * [endOffset], seen both through [toJdn] one second either side of each midnight and through `atStartOfDayIn`.
     */
    private fun civilDayMatches(
        zone: TimeZone,
        date: LocalDate,
        startOffset: UtcOffset,
        endOffset: UtcOffset,
    ): Boolean {
        val start = midnight(date, startOffset)
        val next = midnight(date.plus(1, DateTimeUnit.DAY), endOffset)
        val day = date.toJdn().value
        val expected = listOf(day - 1, day, day, day + 1).map(::Jdn)
        val found = listOf(start - 1.seconds, start, next - 1.seconds, next).map { it.toJdn(zone) }
        return found == expected && date.atStartOfDayIn(zone) == start
    }

    private fun midnight(
        date: LocalDate,
        offset: UtcOffset,
    ): Instant = Instant.fromEpochSeconds(date.toEpochDays() * SECONDS_PER_DAY - offset.totalSeconds)

    private fun probe(epochDay: Long): Instant =
        Instant.fromEpochSeconds(epochDay * SECONDS_PER_DAY + PROBE_SECOND_OF_DAY)
}
