/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.calendar

import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import ir.taqvim.core.model.CalendarDate
import ir.taqvim.core.model.CalendarSystem
import ir.taqvim.core.model.Jdn
import ir.taqvim.core.testing.GoldenFile
import org.junit.jupiter.api.Test

/**
 * T-108 against every Rosh Hashanah, Yom Kippur, first day of Succoth, first day of Hanukkah, first day of Pesach and
 * Shavuot the U.S. Naval Observatory publishes for the Gregorian years 360-9999 (golden/usno, generated by
 * tools/usno/usno_jewish_observances.py).
 */
class UsnoJewishObservancesTest {
    /** A published [observance] of [hebrewYear] on [civilDate] (Julian before 1582-10-15, Gregorian from then on). */
    private data class Record(
        val hebrewYear: Int,
        val observance: JewishObservance,
        val civilDate: String,
    )

    private val rows =
        GoldenFile
            .load("golden/usno/jewish-observances-360-9999.csv")
            .lines
            .drop(1)
            .map { it.split(',') }

    private val records =
        rows.flatMap { row ->
            JewishObservance.entries.mapNotNull { observance ->
                row[observance.ordinal + 1].takeIf { it.isNotEmpty() }?.let { Record(row[0].toInt(), observance, it) }
            }
        }

    @Test
    fun `the golden holds every USNO record and only the range ends are empty`() {
        rows.map { it[0].toInt() } shouldBe (FIRST_HEBREW_YEAR..LAST_HEBREW_YEAR).toList()
        records shouldHaveSize RECORDS
        records.filter { it.hebrewYear == FIRST_HEBREW_YEAR }.map { it.observance } shouldBe
            listOf(JewishObservance.PESACH, JewishObservance.SHAVUOT)
        records.filter { it.hebrewYear == LAST_HEBREW_YEAR }.map { it.observance } shouldBe
            listOf(JewishObservance.ROSH_HASHANAH, JewishObservance.YOM_KIPPUR, JewishObservance.SUCCOTH)
        records.count { it.observance == JewishObservance.HANUKKAH } shouldBe LAST_HEBREW_YEAR - FIRST_HEBREW_YEAR - 1
    }

    @Test
    fun `civil dates switch from Julian to Gregorian at the 1582 reform`() {
        civilJdn("1582-10-04").value + 1 shouldBe civilJdn("1582-10-15").value
        julianToJdn(-3_760, 10, 7) shouldBe HebrewCalendar.EPOCH_JDN
        civilJdn("2000-01-01") shouldBe Jdn(J2000_JDN)
    }

    @Test
    fun `every published observance falls on the computed day`() {
        records
            .filterNot { record ->
                val jdn = civilJdn(record.civilDate)
                val computed = JewishObservances.day(record.observance, record.hebrewYear)
                computed.jdn == jdn && HebrewCalendar.fromJdn(jdn) == computed.date
            }.shouldBeEmpty()
    }

    @Test
    fun `every year length implied by consecutive published new years matches`() {
        val newYears =
            records
                .filter { it.observance == JewishObservance.ROSH_HASHANAH }
                .associate { it.hebrewYear to civilJdn(it.civilDate) }
        (FIRST_HEBREW_YEAR + 1 until LAST_HEBREW_YEAR)
            .filterNot { year ->
                HebrewCalendar.yearLength(year).toLong() == newYears.getValue(year + 1) - newYears.getValue(year)
            }.shouldBeEmpty()
    }

    @Test
    fun `each Gregorian year lists exactly the observances USNO gives for it`() {
        val published =
            records
                .filter { it.civilDate >= FIRST_FULL_GREGORIAN_YEAR }
                .groupBy({ it.civilDate.substring(0, 4).toInt() }, { it.observance to it.civilDate })
        (FIRST_FULL_GREGORIAN_YEAR.substring(0, 4).toInt()..LAST_GREGORIAN_YEAR)
            .filterNot { year ->
                val computed =
                    JewishObservances.inGregorianYear(year).map {
                        it.observance to GregorianCalendarSystem.fromJdn(it.jdn).toIsoLikeString()
                    }
                computed == published.getValue(year).sortedBy { it.second }
            }.shouldBeEmpty()
    }

    /** JDN of an ISO-like civil date: Julian before 1582-10-15 (as USNO prints it), Gregorian from then on. */
    private fun civilJdn(iso: String): Jdn {
        val (year, month, day) = iso.split('-').map(String::toInt)
        return if (iso < FIRST_GREGORIAN_DAY) {
            Jdn(julianToJdn(year, month, day))
        } else {
            GregorianCalendarSystem.toJdn(CalendarDate(CalendarSystem.GREGORIAN, year, month, day))
        }
    }

    /**
     * Julian-calendar date to JDN for years after −4800, by the integer month-shift algorithm (E. G. Richards,
     * "Calendars", Explanatory Supplement to the Astronomical Almanac, 3rd ed., §15.11).
     */
    private fun julianToJdn(
        year: Int,
        month: Int,
        day: Int,
    ): Long {
        val shift = (14 - month) / 12
        val shiftedYear = year + 4_800L - shift
        val shiftedMonth = month + 12 * shift - 3
        return day + (153 * shiftedMonth + 2) / 5 + 365 * shiftedYear + shiftedYear / 4 - 32_083
    }

    private companion object {
        const val FIRST_HEBREW_YEAR = 4_120
        const val LAST_HEBREW_YEAR = 13_760
        const val RECORDS = 57_839
        const val FIRST_GREGORIAN_DAY = "1582-10-15"
        const val FIRST_FULL_GREGORIAN_YEAR = "1583-01-01"
        const val LAST_GREGORIAN_YEAR = 9_999
        const val J2000_JDN = 2_451_545L
    }
}
