/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
import com.ibm.icu.text.DateFormatSymbols;
import com.ibm.icu.util.HebrewCalendar;
import com.ibm.icu.util.ULocale;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Writes core/i18n's hebrew-months.properties from Unicode CLDR through the ICU4J public API (F07, T-108).
 * Run from the repository root: javac -cp icu4j-78.3.jar tools/i18n/HebrewMonthsGen.java and
 * java -cp icu4j-78.3.jar:tools/i18n HebrewMonthsGen. Languages whose CLDR data is only the root (English) fallback, or
 * only generic numbered months, are left out (the T-200 policy); HebrewMonthNamesTest re-checks every value.
 */
public final class HebrewMonthsGen {
    private static final String[][] LANGUAGES = {
        {"fa", "fa-IR"}, {"prs", "fa-AF"}, {"ps", "ps"}, {"ar", "ar"}, {"ckb", "ckb"}, {"kmr", "kmr"},
        {"az", "az-Latn"}, {"tr", "tr"}, {"ur", "ur"}, {"ne", "ne"}, {"hi", "hi"}, {"ta", "ta"}, {"bn", "bn"},
        {"tg", "tg"}, {"uz", "uz-Latn"}, {"en", "en"}, {"ru", "ru"}, {"de", "de"}, {"fr", "fr"}, {"es", "es"},
        {"id", "id"}, {"ms", "ms"}, {"zh", "zh-Hans"}, {"ja", "ja"},
    };
    private static final String GENERIC_LANGUAGE = "zh";

    private HebrewMonthsGen() {}

    static String[] names(String tag) {
        ULocale locale = ULocale.forLanguageTag(tag);
        return new DateFormatSymbols(new HebrewCalendar(locale), locale)
            .getMonths(DateFormatSymbols.STANDALONE, DateFormatSymbols.WIDE);
    }

    public static void main(String[] args) throws IOException {
        String root = String.join("|", names("und"));
        List<String> lines = new ArrayList<>();
        lines.add("# Hebrew calendar month names (F07, T-108). Generated by tools/i18n/HebrewMonthsGen.java; do not edit by hand.");
        lines.add("# Source: Unicode CLDR 48 via the ICU4J 78.3 public API (Unicode-3.0; licenses/ICU-LICENSE.txt), standalone wide");
        lines.add("# names in ICU order: Tishri, Heshvan, Kislev, Tevet, Shevat, Adar I, Adar, Nisan, Iyar, Sivan, Tamuz, Av, Elul,");
        lines.add("# Adar II. Omitted: languages whose CLDR data is only the root fallback, and zh (generic numbered months only).");
        List<String> omitted = new ArrayList<>();
        for (String[] language : LANGUAGES) {
            String value = String.join("|", names(language[1]));
            boolean fallback = !language[0].equals("en") && value.equals(root);
            if (fallback || language[0].equals(GENERIC_LANGUAGE)) {
                omitted.add(language[0]);
            } else {
                lines.add(language[0] + ".locale=" + language[1]);
                lines.add(language[0] + ".months=" + value);
            }
        }
        lines.add("omitted=" + String.join(",", omitted));
        Path out = Path.of("core/i18n/src/main/resources/ir/taqvim/core/i18n/hebrew-months.properties");
        Files.write(out, lines, StandardCharsets.UTF_8);
    }
}
