#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/astronomy's golden/usno/solar-eclipses-1800-2050.csv (T-403) from archived USNO API responses.

Usage: usno_solar_eclipses.py <solar-eclipses-raw.json> <output.csv>

The input is the owner-retrieved list of USNO API v4.0.1 "Solar Eclipses Occurring During a Year" responses
(/api/eclipses/solar/year?year=YYYY), one per year, archived byte-for-byte in docs/sources/usno. One row per eclipse
in source order; the date comes from the day/month/year fields and the type is the prefix of the event name before
" Solar Eclipse of", copied as published (runs of spaces in the name are collapsed). An event name whose date
disagrees with those fields fails the build, except for the reviewed conflicts in KNOWN_NAME_CONFLICTS, whose rows
keep the fields' date and say what the name says in the note column; nothing is repaired.
"""
import hashlib
import json
import sys

SOURCE_PATH = "docs/sources/usno/solar-eclipses-raw.json"
TYPES = {"Partial", "Annular", "Total", "Annular-Total"}
MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]
# (year, event name) pairs whose name date contradicts the record's own day/month/year fields in the USNO response.
KNOWN_NAME_CONFLICTS = {(1898, "Annular Solar Eclipse of 18 June 1898")}
HEADER = [
    "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Solar Eclipses Occurring "
    "During a Year (/api/eclipses/solar/year?year=YYYY), years 1800-2050",
    "# url: https://aa.usno.navy.mil/data/api.html",
    "# retrieved: 2026-09-15",
    "# reviewer: pending",
]


def rows(responses):
    years = [response["year"] for response in responses]
    if years != list(range(years[0], years[0] + len(years))):
        raise ValueError("years are not consecutive")
    for response in responses:
        if response["apiversion"] != "4.0.1":
            raise ValueError(f"unexpected API version in {response['year']}")
        for eclipse in response["eclipses_in_year"]:
            name = " ".join(eclipse["event"].split())
            kind, _, rest = name.partition(" Solar Eclipse of ")
            expected = f"{eclipse['day']} {MONTHS[eclipse['month'] - 1]} {eclipse['year']}"
            if kind not in TYPES or eclipse["year"] != response["year"]:
                raise ValueError(f"unexpected event {eclipse!r}")
            note = ""
            if rest != expected:
                if (eclipse["year"], name) not in KNOWN_NAME_CONFLICTS:
                    raise ValueError(f"event name disagrees with its date fields: {eclipse!r}")
                note = f"USNO event name says {rest}"
            date = f"{eclipse['year']:04d}-{eclipse['month']:02d}-{eclipse['day']:02d}"
            yield f"{date},{kind},{SOURCE_PATH}#year={response['year']},{note}"


def main(source, output):
    with open(source, "rb") as handle:
        raw = handle.read()
    body = list(rows(json.loads(raw)))
    digest = hashlib.sha256(raw).hexdigest()
    notes = (
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved JSON archived byte-for-byte in "
        f"{SOURCE_PATH} (sha256={digest}); date is the UT calendar date USNO gives for the eclipse; type is USNO's "
        "event-name prefix; note flags a record whose event name contradicts its own date fields; generated by "
        "tools/usno/usno_solar_eclipses.py, not typed"
    )
    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(HEADER + [notes, "date,type,source,note"] + body) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
