#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/calendar's USNO US daylight saving golden (T-110) from the archived USNO API responses (public domain).

Usage: usno_us_daylight_saving.py [--check]

Reads docs/sources/usno/us-daylight-saving-raw.json (the owner-retrieved USNO Astronomical Applications API v4.0.1
Daylight Saving Time responses for the years 1967-9999, one object per year), verifies it against
docs/sources/usno/SHA256SUMS and writes core/calendar/src/test/resources/golden/usno/us-daylight-saving-1967-9999.csv:
one row per year with the dates USNO gives for "Daylight Saving Time Begins" and "Daylight Saving Time Ends". Dates are
copied as published; nothing is computed or added. Every year must hold exactly one begin and one end record of that
year, and the years must be contiguous. With --check the file is regenerated in memory and compared instead.
"""
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ARCHIVE = "us-daylight-saving-raw.json"
SOURCE = REPO / "docs/sources/usno" / ARCHIVE
SUMS = REPO / "docs/sources/usno/SHA256SUMS"
GOLDEN = REPO / "core/calendar/src/test/resources/golden/usno/us-daylight-saving-1967-9999.csv"
BEGINS = "Daylight Saving Time Begins"
ENDS = "Daylight Saving Time Ends"


def verified_source():
    source = SOURCE.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    listed = {name: value for value, name in (line.split() for line in SUMS.read_text(encoding="utf-8").splitlines())}
    if listed.get(ARCHIVE) != digest:
        sys.exit(f"{ARCHIVE} does not match docs/sources/usno/SHA256SUMS")
    return source, digest


def row(response):
    if response["apiversion"] != "4.0.1":
        sys.exit(f"unexpected API version in {response}")
    events = {record["event"]: record for record in response["data"]}
    if len(response["data"]) != 2 or set(events) != {BEGINS, ENDS}:
        sys.exit(f"unexpected records {response}")
    year = events[BEGINS]["year"]
    if events[ENDS]["year"] != year:
        sys.exit(f"begin and end in different years {response}")
    begins, ends = (f"{year:04d}-{events[e]['month']:02d}-{events[e]['day']:02d}" for e in (BEGINS, ENDS))
    return year, f"{year},{begins},{ends},docs/sources/usno/{ARCHIVE}"


def build():
    source, digest = verified_source()
    rows = [row(response) for response in json.loads(source)]
    years = [year for year, _ in rows]
    if years != list(range(years[0], years[-1] + 1)):
        sys.exit("years must be contiguous")
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, US Daylight Saving "
        f"Time dates, years {years[0]}-{years[-1]}",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved JSON responses archived "
        f"byte-for-byte in docs/sources/usno/{ARCHIVE} (sha256={digest}, listed in docs/sources/usno/SHA256SUMS); "
        f"{2 * len(rows)} records; US national begin and end dates as published; generated by "
        "tools/usno/usno_us_daylight_saving.py, not typed",
        "year,dst_begins,dst_ends,source_file",
    ]
    return "\n".join(header + [text for _, text in rows]) + "\n"


def main(argv):
    text = build()
    if argv[1:] == ["--check"]:
        if GOLDEN.read_text(encoding="utf-8") != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date; rerun tools/usno/usno_us_daylight_saving.py")
        print("up to date")
    elif argv[1:]:
        sys.exit(__doc__)
    else:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(text, encoding="utf-8")
        print(f"{text.count(chr(10)) - 6} rows written")


if __name__ == "__main__":
    main(sys.argv)
