#!/usr/bin/env python3
"""Generate the A-14 USNO sidereal-time golden from the archived raw API responses.

Local apparent sidereal time is the right ascension of the midheaven, so it is what the ascendant, the midheaven
and every Placidus cusp are built on (Houses.ramcDegrees). Published natal charts to check the cusps themselves
against remain unobtainable (DT-018), but this checks the angle they all start from, against a public-domain
reference. Eight places spanning both hemispheres, the prime meridian and both sides of the date line, at 00:00
and 12:00 UT1 on the four solstices and equinoxes of 2026. Run with --check to verify only.
"""
import argparse, datetime, hashlib, json, pathlib

repo = pathlib.Path(__file__).resolve().parents[2]
archive = repo / "docs/sources/usno/sidereal-2026-raw.json"
sums = repo / "docs/sources/usno/SHA256SUMS"
golden = repo / "core/astronomy/src/test/resources/golden/usno/sidereal-2026.csv"
source_file = "docs/sources/usno/sidereal-2026-raw.json"

# name -> latitude, longitude as requested from the API.
PLACES = {
    "Anchorage": (61.2181, -149.9003),
    "Apia": (-13.8333, -171.7667),
    "Berlin": (52.5200, 13.4050),
    "Greenwich": (51.4779, 0.0),
    "Istanbul": (41.0082, 28.9784),
    "Kabul": (34.5553, 69.2075),
    "Sydney": (-33.8688, 151.2093),
    "Tehran": (35.6892, 51.3890),
}
DATES = ["2026-03-21", "2026-06-21", "2026-09-21", "2026-12-21"]
TIMES = ["00:00:00", "12:00:00"]


def hours(text: str) -> float:
    """A USNO h:mm:ss.ssss sidereal time as decimal hours."""
    parts = text.split(":")
    assert len(parts) == 3, text
    return int(parts[0]) + int(parts[1]) / 60 + float(parts[2]) / 3600


def rows() -> list[str]:
    """One CSV row per place, date and UT1 time, with Greenwich and local apparent sidereal time."""
    data = archive.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    expected = {line.split()[1]: line.split()[0] for line in sums.read_text().splitlines() if line.strip()}
    assert expected["sidereal-2026-raw.json"] == digest, "archive checksum mismatch"

    responses = json.loads(data)
    assert len(responses) == len(PLACES) * len(DATES) * len(TIMES), len(responses)
    out = []
    for key in sorted(responses):
        place, date, ut1 = key.split("|")
        latitude, longitude = PLACES[place]
        record = responses[key]
        assert record["apiversion"] == "4.0.1", key
        payload = record["properties"]["data"]
        assert len(payload) == 1, key
        entry = payload[0]
        parsed = datetime.date.fromisoformat(date)
        assert (entry["year"], entry["month"], entry["day"]) == (parsed.year, parsed.month, parsed.day), key
        assert entry["ut1time"] == f"{ut1}.0", (key, entry["ut1time"])
        # last - gast is the longitude in hours, east positive, wrapped into 0..24.
        offset = (hours(entry["last"]) - hours(entry["gast"])) % 24
        assert abs(((longitude / 15) - offset + 12) % 24 - 12) < 1e-3, (key, offset)
        out.append(
            ",".join(
                [
                    date,
                    ut1,
                    place,
                    f"{latitude:.4f}",
                    f"{longitude:.4f}",
                    entry["gast"],
                    entry["last"],
                    entry["eqofeq"],
                    source_file,
                ]
            )
        )
    return out


def text() -> str:
    """The golden file's provenance header and body."""
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Sidereal Time "
        "(/api/siderealtime), eight places at 00:00 and 12:00 UT1 on the 2026 equinoxes and solstices",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-25",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); raw API responses archived byte-for-byte in "
        f"{source_file} (sha256 in docs/sources/usno/SHA256SUMS); gast and last are Greenwich and local apparent "
        "sidereal time in hours, eqofeq the equation of the equinoxes in seconds; local apparent sidereal time is "
        "the right ascension of the midheaven, which every chart angle is built on (A-14); generated by "
        "tools/usno/usno_sidereal_golden.py from the archive, not typed",
        "date,ut1,place,latitude,longitude,gast,last,eqofeq,source",
    ]
    return "\n".join(header + rows()) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the golden matches the archive")
    arguments = parser.parse_args()
    generated = text()
    if arguments.check:
        current = golden.read_text() if golden.exists() else ""
        if current != generated:
            raise SystemExit(f"{golden} is stale; regenerate with tools/usno/usno_sidereal_golden.py")
        print(f"{golden.name} is up to date ({len(generated.splitlines()) - 6} rows)")
    else:
        golden.write_text(generated)
        print(f"wrote {golden} ({len(generated.splitlines()) - 6} rows)")
