#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/calendar's USNO Christian observances golden (T-109) from the archived USNO API responses (public domain).

Usage: usno_christian_observances.py [--check]

Reads docs/sources/usno/christian-observances-raw.json (the owner-retrieved USNO Astronomical Applications API v4.0.1
Christian observances responses for the Gregorian years 1583-9999, one object per year), verifies it against
docs/sources/usno/SHA256SUMS and writes core/calendar/src/test/resources/golden/usno/christian-observances-1583-9999.csv:
one row per year with the Gregorian dates USNO gives for its eight observances. Nothing is computed or added; every
year must hold exactly one record of each observance, in that year. With --check the file is regenerated in memory and
compared instead.
"""
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE_NAME = "christian-observances-raw.json"
SOURCE = REPO / "docs/sources/usno" / SOURCE_NAME
SUMS = REPO / "docs/sources/usno/SHA256SUMS"
GOLDEN = REPO / "core/calendar/src/test/resources/golden/usno/christian-observances-1583-9999.csv"
FIRST_YEAR = 1583
LAST_YEAR = 9999
COLUMNS = {
    "Ash Wednesday": "ash_wednesday",
    "Palm Sunday": "palm_sunday",
    "Good Friday": "good_friday",
    "Easter": "easter",
    "Ascension Day": "ascension_day",
    "Whit Sunday -- Pentecost": "pentecost",
    "Trinity Sunday": "trinity_sunday",
    "First Sunday in Advent": "first_sunday_of_advent",
}


def verified_source():
    source = SOURCE.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    listed = {name: value for value, name in (line.split() for line in SUMS.read_text().splitlines() if line.strip())}
    if listed.get(SOURCE_NAME) != digest:
        sys.exit(f"{SOURCE_NAME} does not match docs/sources/usno/SHA256SUMS")
    return source, digest


def rows(responses):
    by_year = {}
    for response in responses:
        if response["apiversion"] != "4.0.1":
            sys.exit(f"unexpected API version in {response}")
        for record in response["data"]:
            year = record["year"]
            observance = COLUMNS.get(record["observance"])
            dates = by_year.setdefault(year, {})
            if observance is None or observance in dates:
                sys.exit(f"unexpected record {record}")
            dates[observance] = f"{year:04d}-{record['month']:02d}-{record['day']:02d}"
    if sorted(by_year) != list(range(FIRST_YEAR, LAST_YEAR + 1)):
        sys.exit(f"years must be contiguous from {FIRST_YEAR} to {LAST_YEAR}")
    if any(len(dates) != len(COLUMNS) for dates in by_year.values()):
        sys.exit("every year must hold each observance once")
    return [",".join([str(year)] + [by_year[year][column] for column in COLUMNS.values()]) for year in sorted(by_year)]


def build():
    source, digest = verified_source()
    table = rows(json.loads(source))
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Christian observances, "
        f"Gregorian years {FIRST_YEAR}-{LAST_YEAR}",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved JSON responses archived "
        f"byte-for-byte in docs/sources/usno/{SOURCE_NAME} (sha256={digest}, listed in docs/sources/usno/SHA256SUMS); "
        f"{len(table) * len(COLUMNS)} records; Gregorian civil dates as published; generated by "
        "tools/usno/usno_christian_observances.py, not typed",
        "year," + ",".join(COLUMNS.values()),
    ]
    return "\n".join(header + table) + "\n"


def main(argv):
    text = build()
    if argv[1:] == ["--check"]:
        if GOLDEN.read_text(encoding="utf-8") != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date; rerun tools/usno/usno_christian_observances.py")
        print("up to date")
    elif argv[1:]:
        sys.exit(__doc__)
    else:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(text, encoding="utf-8")
        print(f"{text.count(chr(10)) - 6} rows written")


if __name__ == "__main__":
    main(sys.argv)
