#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/astronomy's USNO seasons golden (T-403, DT-012) from the archived USNO API responses (public domain).

Usage: usno_seasons_golden.py [--check]

Reads docs/sources/usno/seasons-raw.json (the owner-retrieved USNO Astronomical Applications API v4.0.1
`/api/seasons?year=YYYY` responses for 1700-2100, one object per year) and writes
core/astronomy/src/test/resources/golden/usno/seasons-1700-2100.csv: one row per March equinox, June solstice,
September equinox and December solstice, as the UT instant USNO publishes (rounded to the minute). Perihelion and
aphelion records are skipped (the astronomy façade has no apsides API). Nothing is computed or added; every year must
hold exactly one of each season event. With --check the file is regenerated in memory and compared instead.
"""
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE_FILE = "docs/sources/usno/seasons-raw.json"
SOURCE = REPO / SOURCE_FILE
SUMS = REPO / "docs/sources/usno/SHA256SUMS"
GOLDEN = REPO / "core/astronomy/src/test/resources/golden/usno/seasons-1700-2100.csv"
EVENTS = {
    (3, "Equinox"): "march_equinox",
    (6, "Solstice"): "june_solstice",
    (9, "Equinox"): "september_equinox",
    (12, "Solstice"): "december_solstice",
}


def rows(responses):
    result = []
    for response in responses:
        year = response["year"]
        if response["apiversion"] != "4.0.1" or response["tz"] != 0 or response["dst"] is not False:
            sys.exit(f"{year}: unexpected response settings")
        found = {}
        for record in response["data"]:
            key = (record["month"], record["phenom"])
            if key not in EVENTS:
                continue
            if record["year"] != year or key in found:
                sys.exit(f"{year}: unexpected record {record}")
            hour, minute = record["time"].split(":")
            found[key] = f"{year:04d}-{record['month']:02d}-{record['day']:02d}T{int(hour):02d}:{int(minute):02d}:00Z"
        if len(found) != len(EVENTS):
            sys.exit(f"{year}: expected {len(EVENTS)} season events, found {len(found)}")
        result += [f"{year},{name},{found[key]},{SOURCE_FILE}" for key, name in EVENTS.items()]
    return result


def build():
    source = SOURCE.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    expected = {line.split()[1]: line.split()[0] for line in SUMS.read_text().splitlines() if line.strip()}
    if expected.get(SOURCE.name) != digest:
        sys.exit(f"{SOURCE_FILE}: checksum does not match docs/sources/usno/SHA256SUMS")
    responses = json.loads(source)
    years = [response["year"] for response in responses]
    if years != list(range(1700, 2101)):
        sys.exit("seasons-raw.json must hold the years 1700-2100 in order")
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Earth's Seasons and "
        "Apsides (/api/seasons?year=YYYY), years 1700-2100",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved JSON responses archived "
        f"byte-for-byte in {SOURCE_FILE} (sha256={digest}, listed in docs/sources/usno/SHA256SUMS); times are UT "
        "(tz 0) rounded to the minute; perihelion and aphelion are in apsides-1700-2100.csv; generated by "
        "tools/usno/usno_seasons_golden.py from the archive, not typed",
        "gregorian_year,event,instant_ut,source_file",
    ]
    return "\n".join(header + rows(responses)) + "\n"


def main(argv):
    text = build()
    if argv[1:] == ["--check"]:
        if GOLDEN.read_text(encoding="utf-8") != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date; rerun tools/usno/usno_seasons_golden.py")
        print("up to date")
    elif argv[1:]:
        sys.exit(__doc__)
    else:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(text, encoding="utf-8")
        print(f"{text.count(chr(10)) - 6} rows written")


if __name__ == "__main__":
    main(sys.argv)
