#!/usr/bin/env python3
"""Generate the T-407/T-401 USNO sunrise, sunset and civil twilight golden from the archived raw API responses.

Covers the 21st of each month of 2026 for Tehran and the four cities DT-011 names (Kabul, Istanbul, Berlin,
Sydney), so the solar engine behind their prayer times and the blue hour's -6 deg boundary have an independent
public-domain reference. USNO publishes civil twilight at a geometric altitude of -6 deg and rise/set at -0.8333
deg (refraction and semidiameter included); the app's blue hour uses an apparent altitude, so the two conventions
differ by the refraction at -6 deg and the comparison carries a tolerance. Run with --check to verify only.
"""
import argparse, datetime, hashlib, json, pathlib

repo = pathlib.Path(__file__).resolve().parents[2]
archive = repo / "docs/sources/usno/twilight-2026-raw.json"
sums = repo / "docs/sources/usno/SHA256SUMS"
golden = repo / "core/astronomy/src/test/resources/golden/usno/twilight-2026.csv"
source_file = "docs/sources/usno/twilight-2026-raw.json"

# name -> latitude, longitude, standard-time offset in hours, as requested from the API.
CITIES = {
    "Tehran": (35.6892, 51.3890, 3.5),
    "Kabul": (34.5553, 69.2075, 4.5),
    "Istanbul": (41.0082, 28.9784, 3.0),
    "Berlin": (52.5200, 13.4050, 1.0),
    "Sydney": (-33.8688, 151.2093, 10.0),
}
PHENOMENA = {
    "Begin Civil Twilight": "civil_dawn",
    "Rise": "sunrise",
    "Upper Transit": "transit",
    "Set": "sunset",
    "End Civil Twilight": "civil_dusk",
}
ORDER = ["civil_dawn", "sunrise", "transit", "sunset", "civil_dusk"]


def rows() -> list[str]:
    """One CSV row per city and date, with the five solar phenomena in local standard time."""
    data = archive.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    expected = {line.split()[1]: line.split()[0] for line in sums.read_text().splitlines() if line.strip()}
    assert expected["twilight-2026-raw.json"] == digest, "archive checksum mismatch"

    responses = json.loads(data)
    assert len(responses) == len(CITIES) * 12, len(responses)
    out = []
    for key in sorted(responses):
        city, date = key.split("|")
        latitude, longitude, offset = CITIES[city]
        record = responses[key]
        assert record["apiversion"] == "4.0.1", key
        payload = record["properties"]["data"]
        assert payload["tz"] == offset, (key, payload["tz"])
        assert not payload["isdst"], f"{key}: standard time was requested, so DST must not apply"
        parsed = datetime.date.fromisoformat(date)
        assert (payload["year"], payload["month"], payload["day"]) == (parsed.year, parsed.month, parsed.day), key
        times = {PHENOMENA[item["phen"]]: item["time"] for item in payload["sundata"] if item["phen"] in PHENOMENA}
        assert set(times) == set(ORDER), (key, sorted(times))
        minutes = [int(times[name][:2]) * 60 + int(times[name][3:]) for name in ORDER]
        assert minutes == sorted(minutes), (key, times)
        out.append(
            ",".join(
                [date, city, f"{latitude:.4f}", f"{longitude:.4f}", f"{offset:g}"]
                + [times[name] for name in ORDER]
                + [source_file]
            )
        )
    return out


def text() -> str:
    """The golden file's provenance header and body."""
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Sun and Moon Data "
        "for One Day (/api/rstt/oneday), the 21st of each month of 2026 for Tehran, Kabul, Istanbul, Berlin and "
        "Sydney",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-25",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); raw API responses archived byte-for-byte in "
        f"{source_file} (sha256 in docs/sources/usno/SHA256SUMS); times are local standard time at the requested "
        "offset with no daylight saving (isdst is false in every response) and are rounded to the minute; USNO "
        "defines civil twilight at a geometric solar altitude of -6° and rise/set at -0.8333° (refraction and "
        "semidiameter included), while the app's blue hour uses an apparent altitude, so the two differ by the "
        "refraction at -6°; generated by tools/usno/usno_twilight_golden.py from the archive, not typed",
        "date,city,latitude,longitude,utc_offset_hours,civil_dawn,sunrise,transit,sunset,civil_dusk,source",
    ]
    return "\n".join(header + rows()) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the golden matches the archive")
    arguments = parser.parse_args()
    generated = text()
    if arguments.check:
        current = golden.read_text() if golden.exists() else ""
        if current != generated:
            raise SystemExit(f"{golden} is stale; regenerate with tools/usno/usno_twilight_golden.py")
        print(f"{golden.name} is up to date ({len(generated.splitlines()) - 6} rows)")
    else:
        golden.write_text(generated)
        print(f"wrote {golden} ({len(generated.splitlines()) - 6} rows)")
