#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/calendar's USNO Islamic observances golden (T-103) from the archived USNO API responses (public domain).

Usage: usno_islamic_observances.py [--check]

Reads docs/sources/usno/islamic-observances-raw.json (the owner-retrieved USNO Astronomical Applications API v4.0.1
Selected Islamic Observances responses for the Gregorian years 622-9999, one object per year) and writes
core/calendar/src/test/resources/golden/usno/islamic-observances-622-9999.csv: one row per Hijri year with the civil
dates USNO gives for 1 Muharram (Islamic New Year), 1 Ramadan and 1 Shawwal. Dates are copied as published: USNO
prints dates before 1582-10-15 in the Julian calendar, so no date may fall in the skipped days 1582-10-05..14. A field
is empty only where the year range of the source ends. Nothing is computed or added; every record must be unique, and
its observance must name a month-1, month-9 or month-10 start. With --check the file is regenerated in memory and
compared instead.
"""
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE = REPO / "docs/sources/usno/islamic-observances-raw.json"
GOLDEN = REPO / "core/calendar/src/test/resources/golden/usno/islamic-observances-622-9999.csv"
OBSERVANCES = ["Islamic New Year", "First Day of Ramadan", "First Day of Shawwal"]
FIRST_GREGORIAN_DAY = (1582, 10, 15)
LAST_JULIAN_DAY = (1582, 10, 4)


def civil_date(record):
    key = (record["year"], record["month"], record["day"])
    if LAST_JULIAN_DAY < key < FIRST_GREGORIAN_DAY:
        sys.exit(f"date in the 1582 calendar reform gap: {record}")
    return f"{record['year']:04d}-{record['month']:02d}-{record['day']:02d}"


def table(responses):
    starts = {}
    for response in responses:
        if response["apiversion"] != "4.0.1":
            sys.exit(f"unexpected API version in {response}")
        for record in response["data"]:
            key = (record["islamicyear"], record["observance"])
            if record["observance"] not in OBSERVANCES or key in starts:
                sys.exit(f"unexpected record {record}")
            starts[key] = civil_date(record)
    years = sorted({year for year, _ in starts})
    if years != list(range(1, years[-1] + 1)):
        sys.exit("Hijri years must be contiguous from 1")
    return [",".join([str(year)] + [starts.get((year, name), "") for name in OBSERVANCES]) for year in years], starts


def build():
    source = SOURCE.read_bytes()
    responses = json.loads(source)
    rows, starts = table(responses)
    if sum(1 for row in rows for field in row.split(",")[1:] if field) != len(starts):
        sys.exit("row fields do not account for every record")
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Selected Islamic "
        "Observances, Gregorian years 622-9999",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved responses archived in "
        f"docs/sources/usno/islamic-observances-raw.json sha256={hashlib.sha256(source).hexdigest()}; {len(starts)} "
        "records; dates are civil dates as published — Julian calendar before 1582-10-15, Gregorian from then on; "
        "an empty field lies past the source's last Gregorian year; generated by tools/usno/usno_islamic_observances.py",
        "hijri_year,muharram_1,ramadan_1,shawwal_1",
    ]
    return "\n".join(header + rows) + "\n"


def main(argv):
    text = build()
    if argv[1:] == ["--check"]:
        if GOLDEN.read_text(encoding="utf-8") != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date; rerun tools/usno/usno_islamic_observances.py")
        print("up to date")
    elif argv[1:]:
        sys.exit(__doc__)
    else:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(text, encoding="utf-8")
        print(f"{text.count(chr(10)) - 6} rows written")


if __name__ == "__main__":
    main(sys.argv)
