#!/usr/bin/env python3
# Copyright (c) 2026 Saman Sohani. All Rights Reserved.
# Proprietary and confidential. See the LICENSE file in the repository root.
"""Builds core/astronomy's USNO Earth apsides golden (T-403) from the archived USNO API responses (public domain).

Usage: usno_apsides_golden.py [--check]

Reads docs/sources/usno/seasons-raw.json (the owner-retrieved USNO Astronomical Applications API v4.0.1
`/api/seasons?year=YYYY` responses for 1700-2100, one object per year) and writes
core/astronomy/src/test/resources/golden/usno/apsides-1700-2100.csv: one row per perihelion and aphelion of the
Earth, as the UT instant USNO publishes (rounded to the minute). The equinox and solstice records of the same responses
are in seasons-1700-2100.csv (tools/usno/usno_seasons_golden.py). Nothing is computed or added; every year must hold
one aphelion and at most two perihelia, and all events must alternate. With --check the file is regenerated in memory
and compared instead.
"""
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE_FILE = "docs/sources/usno/seasons-raw.json"
SOURCE = REPO / SOURCE_FILE
SUMS = REPO / "docs/sources/usno/SHA256SUMS"
GOLDEN = REPO / "core/astronomy/src/test/resources/golden/usno/apsides-1700-2100.csv"
EVENTS = {"Perihelion": "perihelion", "Aphelion": "aphelion"}


def events(responses):
    result = []
    for response in responses:
        year = response["year"]
        if response["apiversion"] != "4.0.1" or response["tz"] != 0 or response["dst"] is not False:
            sys.exit(f"{year}: unexpected response settings")
        found = []
        for record in response["data"]:
            if record["phenom"] not in EVENTS:
                continue
            if record["year"] != year:
                sys.exit(f"{year}: unexpected record {record}")
            hour, minute = record["time"].split(":")
            instant = f"{year:04d}-{record['month']:02d}-{record['day']:02d}T{int(hour):02d}:{int(minute):02d}:00Z"
            found.append((instant, EVENTS[record["phenom"]]))
        # A perihelion falls around 2-5 January, so a calendar year can hold none (it slipped to 31 December of the
        # year before) or two; alternation across all years is checked below.
        names = [name for _, name in found]
        if names.count("aphelion") != 1 or names.count("perihelion") > 2:
            sys.exit(f"{year}: expected one aphelion and at most two perihelia, found {found}")
        result += [(year, name, instant) for instant, name in sorted(found)]
    for (_, first, _), (year, second, _) in zip(result, result[1:]):
        if first == second:
            sys.exit(f"{year}: apsides do not alternate")
    return result


def build():
    source = SOURCE.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    expected = {line.split()[1]: line.split()[0] for line in SUMS.read_text().splitlines() if line.strip()}
    if expected.get(SOURCE.name) != digest:
        sys.exit(f"{SOURCE_FILE}: checksum does not match docs/sources/usno/SHA256SUMS")
    responses = json.loads(source)
    if [response["year"] for response in responses] != list(range(1700, 2101)):
        sys.exit("seasons-raw.json must hold the years 1700-2100 in order")
    header = [
        "# source: U.S. Naval Observatory, Astronomical Applications Department — API v4.0.1, Earth's Seasons and "
        "Apsides (/api/seasons?year=YYYY), years 1700-2100",
        "# url: https://aa.usno.navy.mil/data/api.html",
        "# retrieved: 2026-09-15",
        "# reviewer: pending",
        "# notes: US government work (public domain, 17 U.S.C. 105); owner-retrieved JSON responses archived "
        f"byte-for-byte in {SOURCE_FILE} (sha256={digest}, listed in docs/sources/usno/SHA256SUMS); times are UT "
        "(tz 0) rounded to the minute; perihelion and aphelion of the Earth's center (equinoxes and solstices are in "
        "seasons-1700-2100.csv); generated by tools/usno/usno_apsides_golden.py from the archive, not typed",
        "gregorian_year,event,instant_ut,source_file",
    ]
    rows = [f"{year},{name},{instant},{SOURCE_FILE}" for year, name, instant in events(responses)]
    return "\n".join(header + rows) + "\n"


def main(argv):
    text = build()
    if argv[1:] == ["--check"]:
        if GOLDEN.read_text(encoding="utf-8") != text:
            sys.exit(f"{GOLDEN.relative_to(REPO)} is out of date; rerun tools/usno/usno_apsides_golden.py")
        print("up to date")
    elif argv[1:]:
        sys.exit(__doc__)
    else:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(text, encoding="utf-8")
        print(f"{text.count(chr(10)) - 6} rows written")


if __name__ == "__main__":
    main(sys.argv)
