/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.feature.map

import androidx.compose.runtime.Immutable
import java.security.MessageDigest

/**
 * The bundled vector data of the map, lines as flattened (x, y) pairs in map units: Natural Earth 1:110m land rings and
 * country boundary lines (public domain; `assets/map/world-110m.txt`), the Natural Earth 1:10m time-zone bands and
 * their boundaries (public domain, 2012 shapes; `assets/map/time-zones-10m.txt`) and the plate-id boundaries of the
 * Matthews et al. (2016) present-day static plate polygons (CC BY 4.0, simplified; `assets/map/plates-matthews-2016.txt`).
 * Generated by the scripts in `tools/geodata/`.
 */
@Immutable
class WorldOutline(
    val land: List<FloatArray>,
    val borders: List<FloatArray>,
    val timeZones: TimeZoneBands = TimeZoneBands(),
    val plates: List<PlateBoundary> = emptyList(),
)

/**
 * A time-zone band (one polygon of the source). [zoneId] is the IANA zone of the most populous catalog city inside it
 * (or inside another polygon of its 2012 region), `null` when it has none; the app computes the band's offset from that
 * zone. [offset2012Minutes] is the source's offset, used only to decide the boundaries of bands without a zone. [label]
 * is where the band's offset is written. [otherZoneIds] are the zones of other catalog places inside the band whose
 * offsets differed from [zoneId]'s when the asset was generated (review I09); the app compares them at the shown moment.
 */
@Immutable
data class TimeZoneBand(
    val zoneId: String?,
    val offset2012Minutes: Int,
    val label: MapPoint,
    val areaKm2: Long,
    val otherZoneIds: List<String> = emptyList(),
)

/** The boundary [line] between the bands at indices [first] and [second]. */
@Immutable
class ZoneBoundary(
    val first: Int,
    val second: Int,
    val line: FloatArray,
)

/** Every band, in the asset's index order, and the boundaries between them. */
@Immutable
class TimeZoneBands(
    val bands: List<TimeZoneBand> = emptyList(),
    val boundaries: List<ZoneBoundary> = emptyList(),
)

/** A plate boundary [line]; [smallerPlateAreaKm2] is the spherical area of the smaller of the two plates it separates. */
@Immutable
class PlateBoundary(
    val smallerPlateAreaKm2: Long,
    val line: FloatArray,
)

/**
 * Reads the outline assets: `#` header lines, then `L` (land ring) and `B` (country boundary) lines of "lon,lat" pairs,
 * `T <zone|-> <2012 offset minutes> <label lon,lat> <area km²> [zone,zone…]` (a time-zone band, in index order, with
 * its optional other zones),
 * `Z <band> <band> lon,lat …` (a time-zone boundary) and `P <km²> lon,lat …` (a plate boundary), all coordinates in
 * hundredths of a degree.
 */
object WorldOutlineParser {
    const val ASSET: String = "map/world-110m.txt"
    const val TIME_ZONES_ASSET: String = "map/time-zones-10m.txt"
    const val PLATES_ASSET: String = "map/plates-matthews-2016.txt"

    /** Every asset of the map, read together by [parse]. */
    val ASSETS: List<String> = listOf(ASSET, TIME_ZONES_ASSET, PLATES_ASSET)

    private const val HASH_PREFIX = "# body-sha256: "

    /** The parts of one asset [text]. */
    fun parse(text: String): WorldOutline = parse(listOf(text))

    /** The parts of every text in [texts], in order. */
    fun parse(texts: List<String>): WorldOutline {
        val builder = OutlineBuilder()
        texts
            .asSequence()
            .flatMap { text -> text.lineSequence().withIndex() }
            .filter { (_, line) -> line.isNotBlank() && !line.startsWith("#") }
            .forEach { (index, line) -> builder.add(line, index + 1) }
        return builder.build()
    }

    /** Whether the header's `body-sha256` equals the SHA-256 of the body lines joined with "\n". */
    fun bodyHashMatches(text: String): Boolean {
        val lines = text.lines().filter { it.isNotEmpty() }
        val declared = lines.firstOrNull { it.startsWith(HASH_PREFIX) }?.removePrefix(HASH_PREFIX)
        val body = lines.filterNot { it.startsWith("#") }.joinToString("\n")
        val digest = MessageDigest.getInstance("SHA-256").digest(body.toByteArray(Charsets.UTF_8))
        return declared == digest.joinToString("") { "%02x".format(it) }
    }
}

/** Collects the parts of the outline lines, validating each. */
private class OutlineBuilder {
    private val land = mutableListOf<FloatArray>()
    private val borders = mutableListOf<FloatArray>()
    private val bands = mutableListOf<TimeZoneBand>()
    private val zoneBoundaries = mutableListOf<ZoneBoundary>()
    private val plates = mutableListOf<PlateBoundary>()

    fun add(
        line: String,
        number: Int,
    ) {
        val tokens = line.split(' ').filter { it.isNotEmpty() }
        require(line.getOrNull(1) == ' ' && tokens.first().length == 1) { "line $number: expected a one-letter tag" }
        val tag = tokens.first().single()
        require(tag in TAGS) { "line $number: unknown outline part '$tag'" }
        when (tag) {
            'L' -> land += points(tokens.drop(1), number)
            'B' -> borders += points(tokens.drop(1), number)
            'T' -> bands += band(tokens, number)
            'Z' -> zoneBoundaries += zoneBoundary(tokens, number)
            else -> plates += plateBoundary(tokens, number)
        }
    }

    fun build(): WorldOutline {
        zoneBoundaries.forEach { boundary ->
            require(boundary.first in bands.indices && boundary.second in bands.indices) {
                "time-zone boundary between unknown bands ${boundary.first} and ${boundary.second}"
            }
        }
        val timeZones = TimeZoneBands(bands.toList(), zoneBoundaries.toList())
        return WorldOutline(land.toList(), borders.toList(), timeZones, plates.toList())
    }

    private fun band(
        tokens: List<String>,
        number: Int,
    ): TimeZoneBand {
        require(tokens.size == BAND_TOKENS || tokens.size == BAND_TOKENS + 1) {
            "line $number: a band needs a zone, an offset, a label, an area and optionally its other zones"
        }
        val label = pair(tokens[LABEL_TOKEN], number)
        val zoneId = tokens[1].takeUnless { it == NO_ZONE }
        val others = tokens.getOrNull(BAND_TOKENS)?.split(',').orEmpty()
        require(others.none { it.isEmpty() } && (others.isEmpty() || zoneId != null)) {
            "line $number: other zones need a representative zone and non-empty names"
        }
        return TimeZoneBand(
            zoneId = zoneId,
            offset2012Minutes = integer(tokens[2], number),
            label = MapPoint(label.first.toDouble(), label.second.toDouble()),
            areaKm2 = integer(tokens[AREA_TOKEN], number).toLong(),
            otherZoneIds = others,
        )
    }

    private fun zoneBoundary(
        tokens: List<String>,
        number: Int,
    ): ZoneBoundary =
        ZoneBoundary(
            integer(tokens.getOrNull(1), number),
            integer(tokens.getOrNull(2), number),
            points(tokens.drop(BOUNDARY_POINTS_TOKEN), number),
        )

    private fun plateBoundary(
        tokens: List<String>,
        number: Int,
    ): PlateBoundary = PlateBoundary(integer(tokens.getOrNull(1), number).toLong(), points(tokens.drop(2), number))

    private fun points(
        pairs: List<String>,
        number: Int,
    ): FloatArray {
        require(pairs.size >= 2) { "line $number: an outline part needs two points" }
        val values = FloatArray(pairs.size * 2)
        pairs.forEachIndexed { index, token ->
            val (x, y) = pair(token, number)
            values[2 * index] = x
            values[2 * index + 1] = y
        }
        return values
    }

    /** A "lon,lat" pair in hundredths of a degree as map units. */
    private fun pair(
        token: String,
        number: Int,
    ): Pair<Float, Float> {
        val longitude = token.substringBefore(',').toIntOrNull()
        val latitude = token.substringAfter(',', "").toIntOrNull()
        require(longitude != null && latitude != null) { "line $number: '$token' is not lon,lat" }
        return (longitude / HUNDREDTHS + HALF_TURN) / FULL_TURN to (RIGHT_ANGLE - latitude / HUNDREDTHS) / HALF_TURN
    }

    private fun integer(
        token: String?,
        number: Int,
    ): Int = requireNotNull(token?.toIntOrNull()) { "line $number: '$token' is not a whole number" }

    private companion object {
        const val HUNDREDTHS = 100f
        const val HALF_TURN = 180f
        const val FULL_TURN = 360f
        const val RIGHT_ANGLE = 90f
        const val NO_ZONE = "-"
        const val TAGS = "LBTZP"
        const val BOUNDARY_POINTS_TOKEN = 3
        const val BAND_TOKENS = 5
        const val LABEL_TOKEN = 3
        const val AREA_TOKEN = 4
    }
}
