/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.konsist

import java.util.Locale

/**
 * Translation completeness of one module (T-1702).
 *
 * @property sourceCount translatable English resources.
 * @property translated resources present per language (source names only; English counts as complete).
 * @property withComment English resources preceded by a translator comment.
 * @property shortWithoutComment one- or two-word English strings without placeholders and without a comment, the
 *   entries most likely to be ambiguous for translators.
 */
data class ModuleCompleteness(
    val module: String,
    val sourceCount: Int,
    val translated: Map<String, Int>,
    val withComment: Int,
    val shortWithoutComment: Int,
)

/** Builds and renders the translation completeness report (docs/i18n/TRANSLATING.md). */
object TranslationReport {
    private const val SHORT_WORDS = 2
    private const val PERCENT = 100.0
    private const val DECIMALS = 10
    private const val MAIN_SOURCE_SET = "main"

    /** Completeness per module for [languages] (launch languages first; extra folder languages are appended). */
    fun completeness(
        folders: List<ResourceFolder>,
        languages: List<String>,
    ): List<ModuleCompleteness> {
        val allLanguages = allLanguages(folders, languages)
        return folders
            .filter { it.language == null && it.entries.isNotEmpty() }
            .map { source ->
                val translations = folders.filter { it.resDir == source.resDir && it.language != null }
                ModuleCompleteness(
                    module = moduleLabel(source.resDir),
                    sourceCount = source.entries.size,
                    translated = allLanguages.associateWith { count(source, translations, it) },
                    withComment = source.entries.values.count { it.hasComment },
                    shortWithoutComment = source.entries.values.count(::isShortWithoutComment),
                )
            }
    }

    /** Launch languages in order, then any other language that has a resource folder. */
    fun allLanguages(
        folders: List<ResourceFolder>,
        languages: List<String>,
    ): List<String> = (languages + folders.mapNotNull { it.language }.sorted()).distinct()

    /** Percentage of all source resources translated into [language], rounded down to one decimal. */
    fun percent(
        rows: List<ModuleCompleteness>,
        language: String,
    ): Double {
        val source = rows.sumOf { it.sourceCount }
        val done = rows.sumOf { it.translated[language] ?: 0 }
        return if (source == 0) PERCENT else Math.floor(done * PERCENT * DECIMALS / source) / DECIMALS
    }

    /** Markdown report: totals per language, then counts per module for languages that have translations. */
    fun markdown(
        rows: List<ModuleCompleteness>,
        languages: List<String>,
    ): String =
        buildString {
            val source = rows.sumOf { it.sourceCount }
            appendLine("# Translation completeness")
            appendLine()
            appendLine("Generated by `./gradlew :konsist:translationReport` (T-1702). Source language: English.")
            appendLine()
            appendLine("| Language | Translated | Of | Percent |")
            appendLine("|---|---:|---:|---:|")
            languages.forEach { language ->
                val done = rows.sumOf { it.translated[language] ?: 0 }
                appendLine("| $language | $done | $source | ${format(percent(rows, language))} % |")
            }
            appendLine()
            appendModules(rows, languages.filter { language -> rows.any { (it.translated[language] ?: 0) > 0 } })
        }

    /** The same numbers as JSON, for tooling. */
    fun json(
        rows: List<ModuleCompleteness>,
        languages: List<String>,
    ): String =
        buildString {
            append("{\"languages\":{")
            append(languages.joinToString(",") { "\"$it\":${format(percent(rows, it))}" })
            append("},\"modules\":[")
            append(rows.joinToString(",", transform = ::moduleJson))
            append("]}")
        }

    private fun StringBuilder.appendModules(
        rows: List<ModuleCompleteness>,
        languages: List<String>,
    ) {
        appendLine("| Module | Source | ${languages.joinToString(" | ")} | With comment | Short, no comment |")
        appendLine("|---|---:|${languages.joinToString("") { "---:|" }}---:|---:|")
        rows.forEach { row ->
            val counts = languages.joinToString(" | ") { (row.translated[it] ?: 0).toString() }
            val comments = "${row.withComment} | ${row.shortWithoutComment}"
            appendLine("| ${row.module} | ${row.sourceCount} | $counts | $comments |")
        }
    }

    private fun moduleJson(row: ModuleCompleteness): String {
        val translated = row.translated.entries.joinToString(",") { (language, done) -> "\"$language\":$done" }
        return "{\"module\":\"${row.module}\",\"source\":${row.sourceCount},\"translated\":{$translated}," +
            "\"withComment\":${row.withComment},\"shortWithoutComment\":${row.shortWithoutComment}}"
    }

    private fun count(
        source: ResourceFolder,
        translations: List<ResourceFolder>,
        language: String,
    ): Int =
        if (language == TranslatedEntry.SOURCE_LANGUAGE) {
            source.entries.size
        } else {
            translations
                .filter { it.language == language }
                .flatMap { it.entries.keys }
                .toSet()
                .count { it in source.entries }
        }

    /** `feature/about` for `feature/about/src/main/res`; other source sets are named, e.g. `app (debug)`. */
    fun moduleLabel(resDir: String): String {
        val module = resDir.substringBefore("/src/")
        val sourceSet = resDir.substringAfter("/src/", "").substringBefore('/')
        return if (sourceSet.isEmpty() || sourceSet == MAIN_SOURCE_SET) module else "$module ($sourceSet)"
    }

    private fun isShortWithoutComment(entry: StringEntry): Boolean =
        entry is StringEntry.Single &&
            !entry.hasComment &&
            TranslationChecks.placeholders(entry.text).isEmpty() &&
            entry.text
                .trim()
                .split(Regex("\\s+"))
                .size <= SHORT_WORDS

    private fun format(value: Double): String = String.format(Locale.ROOT, "%.1f", value)
}
