/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.nlp

import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import ir.taqvim.core.testing.GoldenFile
import java.io.File
import org.junit.jupiter.api.Test

/**
 * G tests of T-500: a synthetic corpus of 500 phrases whose expected days come from `:core:calendar`, never from the
 * parser. The generator is checked against the committed golden fixture (regenerate with
 * `-Ptaqvim.updateSnapshots=true`), and every fixture phrase must parse to its expected day or range.
 */
class DatePhraseCorpusTest {
    @Test
    fun `fixture equals a fresh generation`() {
        val generated = generate().map { it.toLine() }
        generated shouldHaveSize CORPUS_SIZE
        val file = File(FIXTURE)
        if (System.getProperty("taqvim.updateSnapshots").toBoolean()) {
            file.parentFile.mkdirs()
            file.writeText((HEADER + generated).joinToString("\n", postfix = "\n"))
        }
        GoldenFile.parse(file.readText(), file.name).getOrThrow().lines shouldBe generated
    }

    @Test
    fun `every fixture phrase parses to its expected day`() {
        val rows =
            GoldenFile
                .parse(File(FIXTURE).readText(), FIXTURE)
                .getOrThrow()
                .lines
                .map(CorpusRow::parse)
        rows shouldHaveSize CORPUS_SIZE
        val failures =
            rows.mapNotNull { row ->
                val best = DateParser.parseBest(row.phrase, row.context())
                val matches = best != null && best.jdn == row.start && best.end?.jdn == row.end
                if (matches) null else "${row.id} '${row.phrase}' expected ${row.start}..${row.end}, got $best"
            }
        failures.shouldBeEmpty()
    }

    private companion object {
        const val CORPUS_SIZE = 500
        const val SEED = 500
        const val FIXTURE = "src/test/resources/golden/nlp/date-phrases.tsv"
        const val REPOSITORY = "https://github.com/samansohani78/Taqvim/blob/main"
        val HEADER =
            listOf(
                "# source: SYNTHETIC T-500 date-phrase corpus generated by DatePhraseCorpusTest; not a primary source",
                "# url: $REPOSITORY/core/nlp/src/test/kotlin/ir/taqvim/core/nlp/DatePhraseCorpusTest.kt",
                "# retrieved: 2026-09-13",
                "# reviewer: pending",
                "# notes: synthetic phrases from CLDR month/weekday names (:core:i18n) and invented events; " +
                    "expected JDNs from PersianCalendarSystem, IranIslamicCalendar, GregorianCalendarSystem and " +
                    "addMonths, never from the parser. Columns: id, language;preferredCalendar;referenceGregorian, " +
                    "phrase, startJdn, endJdn (- when not a range)",
            )

        fun generate(): List<CorpusRow> {
            val kit = CorpusKit(SEED)
            return AbsolutePhrases.rows(kit) + RelativePhrases.rows(kit)
        }
    }
}
