/*
 * Copyright (c) 2026 Saman Sohani. All Rights Reserved.
 * Proprietary and confidential. See the LICENSE file in the repository root.
 */
package ir.taqvim.core.nlp

import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.longs.shouldBeLessThan
import io.kotest.matchers.shouldBe
import ir.taqvim.core.testing.GoldenFile
import ir.taqvim.core.testing.TimingTest
import java.io.File
import kotlin.system.measureTimeMillis
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test

/**
 * G and B tests of T-501. The 200 snippets are everyday texts written for this project with dates generated from
 * `:core:calendar` (regenerate with `-Ptaqvim.updateSnapshots=true`); every snippet must yield exactly its expected
 * detections. The benchmark scans 100 KB of those snippets, the densest text the corpus has.
 */
class TextSnippetCorpusTest {
    private fun fixtureRows(): List<SnippetRow> =
        GoldenFile
            .parse(File(FIXTURE).readText(), FIXTURE)
            .getOrThrow()
            .lines
            .map(SnippetRow::parse)

    @Test
    fun `fixture equals a fresh generation`() {
        val generated = TextSnippets.rows(CorpusKit(SEED)).map { it.toLine() }
        generated shouldHaveSize CORPUS_SIZE
        val file = File(FIXTURE)
        if (System.getProperty("taqvim.updateSnapshots").toBoolean()) {
            file.parentFile.mkdirs()
            file.writeText((HEADER + generated).joinToString("\n", postfix = "\n"))
        }
        GoldenFile.parse(file.readText(), file.name).getOrThrow().lines shouldBe generated
    }

    @Test
    fun `every snippet yields exactly its expected dates`() {
        val rows = fixtureRows()
        rows shouldHaveSize CORPUS_SIZE
        val failures =
            rows.mapNotNull { row ->
                val found =
                    TextDateDetector.detect(row.text, row.context()).map {
                        ExpectedDate(it.span, it.best.jdn, it.best.end?.jdn)
                    }
                val message = { "${row.id} '${row.text}' expected ${SnippetRow.describe(row.expected)}, got " }
                if (found == row.expected) null else message() + SnippetRow.describe(found)
            }
        failures.joinToString("\n") shouldBe ""
        rows.count { it.expected.isEmpty() } shouldBe NEGATIVES
    }

    @Test
    @Tag(TimingTest.TAG)
    fun `100 KB of text is scanned in less than 50 ms`() {
        val rows = fixtureRows()
        val text = StringBuilder()
        var expected = 0
        var next = 0
        while (text.length < TEXT_CHARS) {
            val row = rows[next++ % rows.size]
            text.append(row.text).append('\n')
            expected += row.expected.size
        }
        val context = rows.first().context()
        repeat(WARM_UP_RUNS) { TextDateDetector.detect(text.toString(), context) }

        val best = (1..MEASURED_RUNS).minOf { measureTimeMillis { TextDateDetector.detect(text.toString(), context) } }

        best shouldBeLessThan BUDGET_MILLIS
        TextDateDetector.detect(text.toString(), context).size shouldBe expected
    }

    private companion object {
        const val CORPUS_SIZE = 200
        const val NEGATIVES = 24
        const val SEED = 501
        const val TEXT_CHARS = 100_000
        const val WARM_UP_RUNS = 3
        const val MEASURED_RUNS = 5
        const val BUDGET_MILLIS = 50L
        const val FIXTURE = "src/test/resources/golden/nlp/text-snippets.tsv"
        const val REPOSITORY = "https://github.com/samansohani78/Taqvim/blob/main"
        val HEADER =
            listOf(
                "# source: SYNTHETIC T-501 snippet corpus generated by TextSnippetCorpusTest; not a primary source",
                "# url: $REPOSITORY/core/nlp/src/test/kotlin/ir/taqvim/core/nlp/SnippetTemplates.kt",
                "# retrieved: 2026-09-13",
                "# reviewer: pending",
                "# notes: everyday messages written for this project (no copied text) with CLDR month/weekday names " +
                    "(:core:i18n); expected JDNs from PersianCalendarSystem, IranIslamicCalendar and " +
                    "GregorianCalendarSystem, never from the detector. Columns: id, " +
                    "language;preferredCalendar;referenceGregorian, text, detections as " +
                    "firstChar-lastChar:startJdn[..endJdn] joined by | (- when none)",
            )
    }
}
